import type { HeroDef, Passive } from "./heroes";
import { MAGA_DEATH } from "./barks.ts";

export type RoleBand = "tank" | "fighter" | "assassin" | "mage" | "marksman" | "support" | "controller";
export type Difficulty = 1 | 2 | 3;
export type PassiveKind =
  | "heat"
  | "vamp"
  | "haste"
  | "mark"
  | "guard"
  | "rage"
  | "link"
  | "ambush"
  | "zone"
  | "tauntwall"
  | "barrage";

export type VoicePack = {
  select: string;
  ult: string;
  death: string;
  win: string;
  kill: string;
  casts: string[];
};

export type KitPatch = {
  difficulty: Difficulty;
  band: RoleBand;
  kind: PassiveKind;
  stack: string;
  bio: string;
  personality: string;
  style: string;
  hpRegen: number;
  manaRegen: number;
  aspd: number;
  mr: number;
  passive: Passive;
  voice: VoicePack;
  blurbs?: Partial<Record<"Q" | "W" | "E" | "R", string>>;
};

function V(select: string, ult: string, death: string, win: string, kill: string, ...casts: string[]): VoicePack {
  return { select, ult, death, win, kill, casts };
}

function K(
  difficulty: Difficulty,
  band: RoleBand,
  kind: PassiveKind,
  stack: string,
  pname: string,
  pblurb: string,
  bio: string,
  personality: string,
  style: string,
  hpRegen: number,
  manaRegen: number,
  aspd: number,
  mr: number,
  voice: VoicePack,
  blurbs?: KitPatch["blurbs"],
): KitPatch {
  return {
    difficulty,
    band,
    kind,
    stack,
    bio,
    personality,
    style,
    hpRegen,
    manaRegen,
    aspd,
    mr,
    passive: { name: pname, blurb: pblurb },
    voice,
    blurbs,
  };
}

const FALLBACK = K(
  2,
  "fighter",
  "heat",
  "Heat",
  "Campus Heat",
  "Spells build Heat. The ultimate spends it for extra punch.",
  "A campus kit with a job on the field.",
  "Shows up.",
  "Cast, stack, spend.",
  2.4,
  6,
  1.08,
  4,
  V("Locked in.", "Now.", "I'm down.", "Campus holds.", "Stay down.", "Go.", "Move.", "Hold.", "Now.", "Again."),
);

export const KITS: Record<string, KitPatch> = {
  riot: K(
    1, "fighter", "heat", "Spirit",
    "Homecoming Heat",
    "Q and E stack Spirit. At five stacks, swings reach farther. R spends Spirit on a louder blast.",
    "Homecoming captain who treats every lane like a pep rally that got out of hand.",
    "Loud, loyal, first through the door.",
    "Stack Spirit, dash in, spend the nova.",
    3.2, 6.2, 1.02, 4,
    V("Riot Cap. Let's go.", "UPRISING!", "Spirit's out.", "Homecoming holds.", "Sit down.", "Slash!", "Breakaway!", "Surge!", "Parade!", "Yell!"),
    { Q: "Cone that stacks Spirit.", W: "Dash. Next swing hits harder if Spirit is hot.", E: "Attack faster. Builds Spirit.", R: "Spends Spirit. Bigger blast at five stacks." },
  ),
  mascot: K(
    1, "tank", "tauntwall", "Foam",
    "Foam Wall",
    "Taunt raises a foam-finger shield. The bird soaks the first hits.",
    "A rented bird suit with a union card and a death wish.",
    "Cheerful, indestructible, slightly unhinged.",
    "Stun, shield, force the fight, charge the parade.",
    4.4, 5.5, 1.12, 8,
    V("Mascot in.", "PARADE!", "Suit's ripped.", "We won homecoming.", "Tweet that.", "Bump!", "Spirit up!", "Heckle!", "Parade!", "Go birds!"),
    { Q: "Stun the front. Starts the soak.", W: "Foam shield. Pairs with the taunt wall.", E: "Taunt nearby rivals and raise a free shield.", R: "Charge that knocks the line aside." },
  ),
  gavel: K(
    2, "tank", "guard", "Order",
    "Closed Session",
    "Drop under a third health and the bench throws a one-time shield.",
    "Campus authority in a robe that has never lost a hearing.",
    "Dry, final, allergic to appeals.",
    "Stun the carry, hold space, blast the room.",
    4.1, 6, 1.1, 8,
    V("The dean will see you.", "EXPELLED.", "Overruled.", "Hearing adjourned.", "Held in contempt.", "Crack!", "Closed!", "Hold!", "Out!", "Order!"),
    { Q: "Stun. Marks the hearing.", W: "Shield the office door.", E: "Slow a knot so Q lands.", R: "Blast the hearing room." },
  ),
  boiler: K(
    2, "tank", "rage", "Pressure",
    "Overpressure",
    "Under 40% health the plant swings faster. Hurt, then hotter.",
    "Night-shift steam tech who talks to valves like they owe rent.",
    "Sweaty, stubborn, proud of the scars.",
    "Cone, shield, dash through, detonate.",
    4.2, 5.4, 1.1, 7,
    V("Plant's live.", "BLOWDOWN!", "Valve's gone.", "Steam holds.", "Cooked.", "Burst!", "Door!", "Vent!", "Blow!", "Hot!"),
    { Q: "Steam cone. Safe poke.", W: "Plate shield while Pressure builds.", E: "Dash the plant. Reposition the nova.", R: "Detonate the boiler." },
  ),
  mason: K(
    1, "tank", "guard", "Mortar",
    "Course Wall",
    "Low health sets a mortar shield once. The wall comes back later.",
    "Bricklayer who treats the quad like a job site that never ends.",
    "Quiet, heavy, immovable.",
    "Stun, wall, cement feet, drop the arch.",
    4.5, 5.2, 1.14, 8,
    V("Mason on site.", "KEYSTONE.", "Scaffold's down.", "Arch holds.", "Cured.", "Trowel!", "Wall!", "Wet!", "Drop!", "Brick!"),
    { Q: "Stun with a wet brick.", W: "Mortar shield.", E: "Slow in wet cement. Sets up Q.", R: "Drop the arch on the lane." },
  ),
  janitor: K(
    1, "support", "link", "Closet",
    "Night Shift",
    "Heals grow when two allies stand in the mop radius.",
    "Graveyard porter with a master key and no patience for blood on tile.",
    "Tired, kind, will mop you off the map.",
    "Slow, shield, heal the line, lock the hall.",
    3.6, 8.2, 1.1, 6,
    V("Night porter.", "LOCKDOWN.", "Bucket's empty.", "Floors are clean.", "Wiped.", "Wet!", "Mop!", "Aid!", "Lock!", "Shift!"),
    { Q: "Slow a slick. Hold people for the heal.", W: "Wringer shield.", E: "Heal. Stronger with allies in range.", R: "Blast the corridor after the mop." },
  ),
  coach: K(
    2, "fighter", "rage", "PR",
    "Personal Record",
    "Low health is a PR. Attack speed climbs when the tank is leaking.",
    "Weight-room lifer who spots strangers and screams numbers.",
    "Loud encouragement as a weapon.",
    "Cone, swing faster, dash the rack, drop plates.",
    3.4, 6, 1.0, 5,
    V("Coach is in.", "MAX OUT!", "Spot me.", "Room's ours.", "Light weight.", "Plates!", "PR!", "Spot!", "Max!", "Lift!"),
    { Q: "Iron cone.", W: "Attack faster. Pairs with low-health rage.", E: "Dash to the rack.", R: "Nova of dropped plates." },
  ),
  bus: K(
    1, "tank", "guard", "Yellow",
    "Yellow Wall",
    "Low health raises the bus side once. Kids stay on the bus.",
    "Activity bus that has hit every curb on campus and kept rolling.",
    "Patient, rectangular, inevitable.",
    "Stun the bumper, shield, pull out, field trip.",
    4.6, 5, 1.16, 8,
    V("Bus is here.", "FIELD TRIP.", "Flat tire.", "We're back by six.", "Door's closed.", "Brake!", "Wall!", "Pull!", "Trip!", "Honk!"),
    { Q: "Stun the bumper.", W: "Bus-side shield.", E: "Dash down the curb.", R: "Charge and detonate." },
  ),
  cadet: K(
    2, "fighter", "heat", "Cadence",
    "Dress Right",
    "Drill stacks Cadence. Five stacks lengthen the swing. R spends the count.",
    "ROTC captain who salutes incoming skillshots.",
    "Crisp, earnest, slightly too awake.",
    "Cone, dash, cadence, parade blast.",
    3.1, 6.2, 1.02, 5,
    V("Cadet Captain.", "PASS IN REVIEW!", "Fall out.", "Formation holds.", "At ease.", "Dress!", "Double!", "Count!", "Review!", "Sir!"),
    { Q: "Cone of drill. Stacks Cadence.", W: "Dash the formation.", E: "Attack faster. Builds Cadence.", R: "Spends Cadence on the parade ground." },
  ),
  pledge: K(
    2, "tank", "tauntwall", "Letters",
    "Brotherhood",
    "Taunt paints a lettered shield. The porch soaks the swing.",
    "House pledge who would eat a tackle for a letter jacket.",
    "Eager, loud, one brain cell, all heart.",
    "Stun, taunt, shield, rush the lawn.",
    3.8, 5.6, 1.08, 7,
    V("Pledge reporting.", "RUSH WEEK!", "Hell week.", "House stands.", "Pledge down — I mean they down.", "Keg!", "Bros!", "Wall!", "Rush!", "Yeah!"),
    { Q: "Stun with a cold barrel.", W: "Taunt the porch and raise a free shield.", E: "Lettered wall.", R: "Charge the lawn." },
  ),
  bass: K(
    2, "tank", "zone", "Downbeat",
    "On the One",
    "Slows linger. The drumline owns the ground after a hit.",
    "Biggest drum on the field. Walks like a tempo marking.",
    "Steady, deafening, immovable on the one.",
    "Stun, wall, slow the step, halftime nova.",
    4.2, 5.8, 1.14, 7,
    V("Bass is in.", "HALFTIME.", "Dropped the stick.", "Cadence holds.", "Downbeat.", "One!", "Wall!", "Slow!", "Half!", "Boom!"),
    { Q: "Stun on the one.", W: "Bass shield.", E: "Slow the rival step. Zone lingers.", R: "Nova of the big drum. Leaves a hush." },
  ),
  chef: K(
    2, "fighter", "link", "Seconds",
    "Meal Plan",
    "Heals feed more when the line is stacked. Allies in range eat better.",
    "Dining-hall lifer with a ladle and a union grievance.",
    "Warm, armed, will serve you twice.",
    "Cone, heal the line, tray armor, closing bell.",
    3.5, 7.8, 1.06, 5,
    V("Kitchen's open.", "CLOSING BELL.", "88'd.", "Line's fed.", "Next.", "Ladle!", "Seconds!", "Tray!", "Closed!", "Hot!"),
    { Q: "Gravy cone.", W: "Heal the line. Stronger with friends.", E: "Plastic shield.", R: "Blast the servery." },
  ),

  spike: K(
    2, "assassin", "haste", "Kick",
    "Negative Split",
    "Dashes leave a kick of move speed. First stride after a dash is free.",
    "Lane sprinter who false-starts on purpose.",
    "Wired, lean, allergic to standing still.",
    "Cone, kick dash, swing faster, anchor charge.",
    2.2, 6, 0.98, 3,
    V("On the blocks.", "ANCHOR LEG!", "False start.", "Tape's ours.", "Split.", "Gun!", "Kick!", "Split!", "Anchor!", "Go!"),
    { Q: "Cone off the blocks.", W: "Dash. Grants Kick speed.", E: "Attack faster after the kick.", R: "Charge and burst. Reset if it kills." },
  ),
  foil: K(
    3, "assassin", "ambush", "Right",
    "Right of Way",
    "The first hit after a dash is a touch. Woods make it cleaner.",
    "Club fencer who treats the river like a piste.",
    "Precise, smug, counts touches out loud.",
    "Stun, flèche, riposte, steel nova.",
    2.0, 6.4, 0.96, 3,
    V("En garde.", "TOUCHÉ.", "Off target.", "Bout's ours.", "Touch.", "Lunge!", "Flèche!", "Riposte!", "Touché!", "Allez!"),
    { Q: "Stun on the point. Lands after a dash.", W: "Dash past the guard. Arms the touch.", E: "Attack faster.", R: "Nova of steel. Kill refunds the dash." },
  ),
  skate: K(
    2, "assassin", "haste", "Grind",
    "Curb Cut",
    "Dashes leave grind speed. The rail is faster than the lane.",
    "Quad-skate roamer who treats curbs as public transit.",
    "Loose, grinning, never on the sidewalk.",
    "Cone, kickflip, jam speed, bowl charge.",
    2.1, 5.8, 0.97, 2,
    V("Skates on.", "BOWL RUN!", "Yard sale.", "Rail's ours.", "Sick.", "Curb!", "Flip!", "Jam!", "Bowl!", "Ollie!"),
    { Q: "Cone of a grind.", W: "Dash the rail. Grants grind speed.", E: "Attack faster.", R: "Charge the bowl. Kill resets the flip." },
  ),
  shot: K(
    2, "marksman", "mark", "Red-Eye",
    "Red Eye",
    "Slows stamp a Red-Eye. The next bolt cashes it.",
    "Yearbook shooter who only photographs people mid-mistake.",
    "Quiet, invasive, always one click late on purpose.",
    "Bolt, slow the subject, dash frames, cover shot.",
    1.8, 7.2, 1.18, 3,
    V("Camera's hot.", "COVER SHOT.", "Card's full.", "Front page.", "Got it.", "Flash!", "Red-eye!", "Darkroom!", "Cover!", "Click!"),
    { Q: "Bolt a portrait. Cashes a Red-Eye.", W: "Slow the subject and stamp Red-Eye.", E: "Dash between frames.", R: "Cover bolt. Spends the stamp for extra." },
  ),
  flyer: K(
    2, "assassin", "haste", "Toss",
    "Basket Toss",
    "Dashes leave toss speed. The flyer never lands where you looked.",
    "Cheer flyer who treats gravity like a suggestion.",
    "Bright, airborne, slightly concussed.",
    "Stun, liberty dash, spirit speed, stunt charge.",
    2.0, 6.1, 0.98, 2,
    V("Flyer up.", "STUNT SEQUENCE!", "Cradle missed.", "Pyramid holds.", "Stuck it.", "Toss!", "Liberty!", "Spirit!", "Stunt!", "Go!"),
    { Q: "Stun on the catch.", W: "Dash the pyramid. Grants toss speed.", E: "Attack faster.", R: "Charge and burst." },
  ),
  alto: K(
    2, "marksman", "mark", "Reed",
    "Solo Chair",
    "Slows seat a Reed mark. The next bolt is the solo.",
    "Marching alto who plays through anything, including sense.",
    "Dramatic, pitchy, always first chair in their head.",
    "Bolt, gliss slow, slide dash, solo collect.",
    1.9, 7.4, 1.18, 3,
    V("Alto in.", "SOLO.", "Reed split.", "Stand holds.", "Feature.", "Cut!", "Gliss!", "Slide!", "Solo!", "And!"),
    { Q: "Bolt a high note. Cashes Reed.", W: "Slow the stand and seat Reed.", E: "Dash the form.", R: "Solo bolt. Spends the seat." },
  ),
  mail: K(
    2, "assassin", "haste", "Loop",
    "Certified",
    "Dashes leave loop speed. The tunnels are faster than the quad.",
    "Mailroom courier who has never used a door they could skip.",
    "Blunt, on-time, will throw a box.",
    "Stun, interoffice dash, certified swings, campus loop.",
    2.2, 5.6, 0.99, 3,
    V("Mailroom.", "CAMPUS LOOP.", "Return to sender.", "Route's done.", "Signed.", "Parcel!", "Office!", "Cert!", "Loop!", "Move!"),
    { Q: "Stun with a box.", W: "Dash the tunnels. Grants loop speed.", E: "Attack faster.", R: "Charge the route. Kill refunds the hop." },
  ),
  intern: K(
    2, "controller", "tauntwall", "Clip",
    "Talking Point",
    "Taunt raises a clipboard shield. The stoop soaks while you talk.",
    "Field intern who will door-knock a teamfight.",
    "Caffeinated, scripted, never blinks.",
    "Cone, canvass dash, taunt the stoop, GOTV charge.",
    2.6, 6.4, 1.04, 4,
    V("Intern on doors.", "GOTV!", "Shift's over.", "Precinct holds.", "Logged.", "Clip!", "Canvass!", "Point!", "Votes!", "Hi!"),
    { Q: "Cone of flyers.", W: "Dash the block.", E: "Taunt the stoop and raise a shield.", R: "Charge the precinct." },
  ),
  bike: K(
    2, "assassin", "haste", "Peloton",
    "Critical Mass",
    "Dashes leave peloton speed. Alleys beat streets.",
    "Bike courier who treats red lights as performance art.",
    "Fast, righteous, one U-lock from a felony.",
    "Stun, cut through, peloton swings, mass charge.",
    2.1, 5.7, 0.97, 3,
    V("Courier on.", "CRITICAL MASS.", "Wrecked.", "Street's ours.", "Trackstand.", "Lock!", "Cut!", "Pack!", "Mass!", "Ride!"),
    { Q: "Stun a rival wheel.", W: "Dash the alley. Grants peloton speed.", E: "Attack faster.", R: "Charge the street. Kill resets the cut." },
  ),
  belfry: K(
    2, "marksman", "mark", "Peal",
    "Noon Bell",
    "Slows ring a Peal. The next bolt collects the hour.",
    "Bell-tower carry who never comes down for lunch.",
    "Distant, punctual, slightly haunted.",
    "Bolt from height, peal slow, stair dash, noon collect.",
    1.7, 7.1, 1.2, 3,
    V("Belfry live.", "NOON BELL.", "Rope's cut.", "Hour holds.", "Tolled.", "Clap!", "Peal!", "Stairs!", "Noon!", "Ring!"),
    { Q: "Bolt from the belfry. Cashes Peal.", W: "Slow the quad and ring Peal.", E: "Dash the spiral.", R: "Noon bolt. Spends the hour." },
  ),
  sack: K(
    2, "assassin", "ambush", "Stall",
    "Around the World",
    "First hit after a dash is a stall. Woods make the circle safer.",
    "Hacky-sack juker who never lets the bag touch grass.",
    "Loose, smiling, impossible to tackle cleanly.",
    "Stun, circle dash, around-the-world swings, drop nova.",
    2.0, 5.5, 0.98, 2,
    V("Circle's up.", "DROP.", "Bag's down.", "Circle holds.", "Stall.", "Foot!", "Circle!", "World!", "Drop!", "Hack!"),
    { Q: "Stun on a stall. Lands after the dash.", W: "Dash the hack circle. Arms the stall.", E: "Attack faster.", R: "Nova of the sack." },
  ),
  snare: K(
    2, "fighter", "heat", "Roll",
    "Flam Stack",
    "Flams stack Roll. Five stacks reach farther. R spends the cadence.",
    "Drumline snare who rudiments in fights.",
    "Tight, proud, counts everything.",
    "Cone, parade dash, roll speed, cadence break.",
    2.4, 6.2, 1.0, 3,
    V("Snare in.", "CADENCE BREAK.", "Stick broke.", "Form holds.", "Flam.", "Flam!", "Step!", "Roll!", "Break!", "Hat!"),
    { Q: "Cone of sticks. Stacks Roll.", W: "Dash the form.", E: "Attack faster. Builds Roll.", R: "Charge and burst. Spends Roll." },
  ),

  desk: K(
    2, "mage", "mark", "Overdue",
    "Collection Due",
    "Slows stamp Overdue. The next bolt collects with fees.",
    "Graveyard librarian who fines people in real time.",
    "Whisper-loud, petty, correct.",
    "Bolt, hush slow, stack walk, collect the fee.",
    1.6, 9.2, 1.2, 5,
    V("Night desk.", "COLLECTION DUE.", "Card revoked.", "Stacks hold.", "Paid.", "Stamp!", "Hush!", "Walk!", "Due!", "Shh."),
    { Q: "Hurl a date stamp. Cashes Overdue.", W: "Slow a hush and stamp Overdue.", E: "Blink between shelves.", R: "Collect bolt. Spends the fee." },
  ),
  ra: K(
    1, "support", "link", "Duty",
    "Duty Round",
    "Heals grow when the floor is stacked. Two residents, bigger bandage.",
    "Hall RA who write-ups people during teamfights.",
    "Tired, fair, clipboard always out.",
    "Bolt, quiet hours, duty heal, fire-drill nova.",
    2.8, 8.6, 1.16, 5,
    V("RA on duty.", "FIRE DRILL.", "Write-up filed.", "Floor's clear.", "Logged.", "Write!", "Quiet!", "Duty!", "Drill!", "Hey."),
    { Q: "Bolt a policy.", W: "Slow the hall.", E: "Heal the floor. Stronger with residents.", R: "Nova the stairwell." },
  ),
  chem: K(
    3, "mage", "zone", "Fume",
    "Exothermic",
    "Rains and novas leave a fume slow. The bench owns the tile.",
    "Chem tech who treats the lane like a hood that never shuts.",
    "Cheerful, hazardous, safety-goggles optional.",
    "Bolt, fume slow, acid rain, bench detonate.",
    1.5, 9.4, 1.18, 5,
    V("Hood's on.", "EXOTHERMIC.", "Spill.", "Yield holds.", "Reacted.", "Pipe!", "Fume!", "Spill!", "Boom!", "Hot!"),
    { Q: "Bolt a reagent.", W: "Slow a cloud. Leaves fumes.", E: "Rain acid. Zone lingers.", R: "Detonate the bench. Leaves a hush." },
  ),
  debate: K(
    2, "controller", "mark", "Ballot",
    "Point of Order",
    "Slows and stuns seat a Ballot. The next bolt is the vote.",
    "Forensics chair who times other people's sentences.",
    "Sharp, smug, never drops a card.",
    "Stun, rebuttal bolt, time slow, ballot collect.",
    1.8, 8.8, 1.16, 5,
    V("Chair recognizes.", "BALLOT.", "Time.", "Case holds.", "Dropped.", "Order!", "Rebut!", "Time!", "Vote!", "Flow!"),
    { Q: "Stun a speaker and seat Ballot.", W: "Bolt the case. Cashes Ballot.", E: "Slow the floor and seat Ballot.", R: "Collect bolt. Spends the vote." },
  ),
  radio: K(
    1, "support", "link", "Request",
    "Dedication",
    "Heals grow when listeners stand close. The booth feeds the room.",
    "Late-slot DJ who dedicates fights to the dining hall.",
    "Warm static, never signs off on time.",
    "Bolt, static slow, dedication heal, sign-off nova.",
    2.4, 8.4, 1.16, 5,
    V("You're on air.", "SIGN-OFF.", "Dead air.", "Booth holds.", "Dedicated.", "Call!", "Static!", "This one's for you.", "Off!", "Keep it here."),
    { Q: "Bolt the request line.", W: "Slow the band.", E: "Heal the listeners. Stronger in a crowd.", R: "Nova the booth." },
  ),
  counsel: K(
    1, "support", "link", "Session",
    "Crisis Line",
    "Heals grow in a circle. Two friends, one session, bigger lift.",
    "Wellness desk that will ground you mid-gank.",
    "Soft voice, iron boundary.",
    "Bolt, grounding slow, session heal, crisis ult-heal.",
    2.9, 8.8, 1.14, 6,
    V("Intake's open.", "CRISIS LINE.", "Session's over.", "Room's safe.", "Noted.", "Form!", "Ground!", "Breathe.", "Line!", "Here."),
    { Q: "Bolt a form.", W: "Slow a panic.", E: "Heal the circle. Stronger with friends.", R: "Big heal. Stronger when the circle is full." },
  ),
  ta: K(
    2, "mage", "mark", "Margin",
    "The Curve",
    "Slows write a Margin. The next bolt is the grade.",
    "Office-hours TA who red-pens people in public.",
    "Tired, exact, will extend your cooldown.",
    "Bolt, extension slow, whiteboard rain, curve collect.",
    1.6, 9.1, 1.18, 5,
    V("Office hours.", "CURVE.", "See me.", "Section holds.", "Marked.", "Pen!", "Extend!", "Board!", "Curve!", "Next."),
    { Q: "Bolt a margin. Cashes the note.", W: "Slow the deadline and write Margin.", E: "Rain notes on a point.", R: "Collect bolt. Spends the grade." },
  ),
  press: K(
    2, "mage", "mark", "Lead",
    "Front Page",
    "Slows set a Lead. The next bolt is the headline.",
    "Student paper editor who fact-checks your death recap.",
    "Ink-stained, caffeinated, never off the record.",
    "Bolt, retraction slow, press-run dash, front page.",
    1.7, 8.9, 1.18, 4,
    V("Copy's in.", "FRONT PAGE.", "Killed the story.", "Ink holds.", "Printed.", "Lead!", "Retract!", "Run!", "Page!", "Quote!"),
    { Q: "Bolt a headline. Cashes Lead.", W: "Slow the copy and set Lead.", E: "Dash the basement.", R: "Collect bolt. Spends the headline." },
  ),
  term: K(
    3, "mage", "zone", "Lag",
    "Kernel Panic",
    "Rains and novas leave lag. The rack owns the tile.",
    "CS-lab terminal that segfaults other people.",
    "Cold, blinking, one compile from god.",
    "Bolt, lag slow, SSH hop, kernel nova.",
    1.4, 9.6, 1.16, 4,
    V("Compile's clean.", "KERNEL PANIC.", "Segfault.", "Rack holds.", "Shipped.", "Error!", "Lag!", "Hop!", "Panic!", "sudo."),
    { Q: "Bolt an error.", W: "Slow the lab. Leaves lag.", E: "Dash a hop.", R: "Detonate the rack. Leaves a hang." },
  ),
  lecture: K(
    2, "mage", "zone", "Clicker",
    "The Final",
    "Rains and novas dim the house. Seats stay slow.",
    "Hundred-level hall that will laser a mid laner.",
    "Projected, bored, huge.",
    "Bolt, dim slow, laser rain, final nova.",
    1.8, 8.7, 1.2, 5,
    V("Clickers out.", "FINAL.", "Class dismissed.", "Hall holds.", "Attendance.", "Click!", "Dim!", "Laser!", "Final!", "Next slide."),
    { Q: "Bolt a slide.", W: "Slow the seats. Dim lingers.", E: "Rain a pointer. Zone stays.", R: "Nova the hall. Leaves a hush." },
  ),
  reg: K(
    2, "controller", "guard", "Hold",
    "Records Hold",
    "Low health seals a records shield once. The file does not drop.",
    "Registrar who can end a semester with a stamp.",
    "Flat, final, no office-hours smile.",
    "Stun, add/drop slow, seal shield, expunge bolt.",
    2.6, 8.2, 1.16, 6,
    V("Records.", "EXPUNGE.", "Hold placed.", "File holds.", "Sealed.", "Hold!", "Drop!", "Seal!", "Gone!", "Next."),
    { Q: "Stun a transcript.", W: "Slow the line.", E: "Records shield. Pairs with the low-health seal.", R: "Collect bolt." },
  ),
  ethics: K(
    1, "support", "link", "Finding",
    "Finding",
    "Heals grow in the chamber. A full panel lifts more.",
    "Review board that sanctions teamfights.",
    "Polite, lethal, always recused from fun.",
    "Bolt, recusal slow, finding heal, sanction nova.",
    2.5, 8.5, 1.16, 5,
    V("Board is seated.", "SANCTION.", "Recused.", "Finding stands.", "Noted.", "Cite!", "Recuse!", "Find!", "Sanction!", "So moved."),
    { Q: "Bolt a case.", W: "Slow the panel.", E: "Heal the room. Stronger with a panel.", R: "Nova the chamber." },
  ),

  "maga-grumptor": K(
    2, "fighter", "heat", "Controversy",
    "Controversy",
    "Q, W, and E stack Controversy. At five, range and damage jump. TOTAL DOMINATION spends the stack.",
    "A red-coat tweeter who treats every lane like a rally lawn.",
    "Louder than the fight. Never logs off.",
    "Shove the first line, rally the lawn, drop a delayed order, then knock the ring.",
    3.6, 6.4, 1.04, 6,
    V("Grump. Tremendous kit.", "TOTAL DOMINATION!", "Fake news.", "We win. Bigly.", "You're fired.", "CAPS LOCK!", "Rally!", "Order!", "DOMINATION!", "Witch hunt!"),
    { Q: "All-caps cone. Builds Controversy.", W: "Attack faster. Lasts longer at high Controversy.", E: "Stun the briefing. Builds Controversy.", R: "Spends Controversy. Five stacks, biggest blast." },
  ),
  "maga-kyleyle": K(
    3, "fighter", "ambush", "Ready",
    "Self-Defense",
    "First hit after Crossing is the counter. Woods make the sidewalk cleaner.",
    "A pale sidewalk fighter who only swings after the dash.",
    "Nervous, armed, writes his own recap.",
    "Stun, cross, shield, stand-your-ground charge.",
    2.6, 6.2, 1.0, 4,
    V("Kyle. Ready.", "STAND YOUR GROUND!", "I was retreating.", "Sidewalk holds.", "Self-defense.", "Counter!", "Crossing!", "Ready!", "Ground!", "Move."),
    { Q: "Stun the sidewalk. Lands after Crossing.", W: "Dash past the line. Arms the counter.", E: "Self-defense shield.", R: "Charge and burst. Kill refunds Crossing." },
  ),
  "maga-alexgroans": K(
    3, "mage", "mark", "Dump",
    "Info Dump",
    "Slows and rains stamp a Dump. Truth Bomb cashes the file.",
    "Late-night booth mage who artillery-fires from the back of the street.",
    "Hoarse, certain, never short on paper.",
    "Mark a far mic, dump the file twice, pin the hour, then a bomb that sticks if marked.",
    1.5, 9.4, 1.2, 5,
    V("Alex. Open phones.", "TRUTH BOMB.", "They're hanging up.", "Booth holds.", "Documented.", "Mic!", "Dump!", "Break!", "BOMB!", "Stay on the line."),
    { Q: "Bolt a late-night take. Cashes Dump.", W: "Rain a dump. Stamps Dump and leaves lag.", E: "Slow the hour and stamp Dump.", R: "Collect bolt. Spends the file." },
  ),
  "maga-rogentor": K(
    2, "controller", "link", "Long-Form",
    "Long Form",
    "Heals grow when guests sit in the booth. The bit runs long.",
    "A studio controller who will talk a teamfight into overtime.",
    "Curious, rambling, always one guest away from a heal.",
    "Pull a guest, heal the booth twice, smoke yourself, then taunt the room twice.",
    2.4, 8.6, 1.14, 5,
    V("Joe. Three hours.", "THREE-HOUR MONOLOGUE!", "We're out of time.", "Studio holds.", "That's the bit.", "Take!", "Guest!", "Smoke!", "MONOLOGUE!", "Jamie, pull that up."),
    { Q: "Bolt a long question.", W: "Heal the studio. Stronger with guests in range.", E: "Slow the guest.", R: "Nova the booth. Leaves a long hush." },
  ),
  "maga-quirk": K(
    2, "fighter", "haste", "Tour",
    "Campus Tour",
    "Dashes leave tour speed. The lawn is a route, not a stage.",
    "Youth motivator who sprints quads and talks over the swing.",
    "Bright, certain, always booking the next lawn.",
    "Mark the first take, stop the tour, load the next swing, then charge the midterm.",
    2.5, 6.4, 0.99, 3,
    V("Quirk. Prove me wrong.", "MIDTERM RALLY!", "Change my mind.", "Lawn holds.", "Noted.", "Prove!", "Tour!", "Point!", "Rally!", "Facts."),
    { Q: "Cone of a campus take.", W: "Dash the quad. Grants tour speed.", E: "Attack faster.", R: "Charge the lawn. Kill refunds the tour." },
  ),
  "maga-tommy": K(
    2, "tank", "tauntwall", "Chant",
    "People's March",
    "Taunt raises a chant shield. The street soaks while you call.",
    "A street tank who turns a sidewalk into a march.",
    "Hoarse, stubborn, always live.",
    "Pull a marcher in, delay a hard line, chant behind a shield, then dash and shove.",
    4.0, 5.8, 1.1, 7,
    V("Tommy. On the street.", "PEOPLE'S MARCH!", "Banned again.", "Street holds.", "Heard.", "Call!", "Ban!", "Chant!", "March!", "Now."),
    { Q: "Stun the front.", W: "Slow the feed.", E: "Taunt nearby rivals and raise a chant shield.", R: "Charge the street." },
  ),
  "maga-elonmolk": K(
    3, "assassin", "haste", "Beta",
    "Beta Release",
    "Dashes leave beta speed. First stride after a hop is the gadget.",
    "A chrome assassin who ships dashes in public.",
    "Restless, certain, the car is always in beta.",
    "Blink off a slow pad, delay a marked drone, speed that pops, then stop into a double stun.",
    1.9, 6.6, 0.95, 2,
    V("Muck. Ship it.", "FULL SELF-DRIVE!", "The car decided.", "Mars later. Lane now.", "Deployed.", "Dash!", "Drone!", "Auto!", "DRIVE!", "Nice."),
    { Q: "Dash the pad. Grants beta speed.", W: "Bolt a gadget.", E: "Attack faster.", R: "Charge and burst. Kill refunds the pad dash." },
  ),
  "maga-boris": K(
    2, "tank", "guard", "Wire",
    "Party Wall",
    "Low health raises a party-wall shield once. The stunt survives.",
    "A rumpled tank who zip-wires into problems and Latin-blusters out.",
    "Jovial, chaotic, always mid-stunt.",
    "Slow the far edge of the speech, zip until you hit, hold a wall that bursts, then knock the chamber.",
    4.1, 6.0, 1.12, 7,
    V("Boris. Onwards.", "GET BREXIT DONE!", "The wire snapped.", "Chamber holds.", "Inverted.", "Bluster!", "Wire!", "Wall!", "DONE!", "Cripes."),
    { Q: "Cone of a speech.", W: "Dash the stunt.", E: "Barrier shield. Pairs with the low-health wall.", R: "Blast the chamber." },
  ),
  "maga-brander": K(
    3, "controller", "mark", "Awake",
    "Unpredictable",
    "Stuns and slows seat Awake. Conspiracy Hour cashes the topic.",
    "A free-thinker mage who changes the subject mid-combo.",
    "Intense, shifting, always one diet from a heal.",
    "A late stun if the topic is marked, pull the panel, heal harder when low, and the next staff hit marks.",
    1.8, 8.8, 1.16, 5,
    V("Brand. Stay awake.", "CONSPIRACY HOUR.", "They cancelled the bit.", "The lion ate.", "Awake.", "Wake!", "Slow!", "Diet!", "HOUR!", "Listen."),
    { Q: "Stun a talking point and seat Awake.", W: "Slow the panel and seat Awake.", E: "Heal the room.", R: "Collect bolt. Spends the topic." },
  ),
  "maga-vestyt": K(
    3, "assassin", "rage", "Service",
    "Momentum",
    "Low health is the drop. Swings speed up when the coat is torn.",
    "A culture assassin who closed-verses through the front line.",
    "Volatile, stylish, Sunday-loud.",
    "The next swing shoves, step back unseen, speed up only when torn, then a late Sunday stun that heals allies.",
    2.8, 6.0, 1.0, 4,
    V("Vest. Closed verse.", "SUNDAY SERVICE!", "They don't know.", "Hall holds.", "Next verse.", "Closed!", "Cut!", "Service!", "SUNDAY!", "Huh."),
    { Q: "Cone of a Sunday take.", W: "Dash the drop.", E: "Attack faster. Pairs with low-health momentum.", R: "Blast the hall." },
  ),
  "maga-steers": K(
    2, "fighter", "tauntwall", "Bit",
    "Crowd Work",
    "Taunt raises a bit-shield. The room soaks while you roast.",
    "A comedy fighter who turns the aisle into a special.",
    "Grinning, mean, always working the room.",
    "Taunt the front row, dash the far side of the aisle, taunt twice, then a late stun on the charge.",
    2.6, 6.2, 1.02, 4,
    V("Steers. Who's here?", "HOUR SPECIAL!", "Tough room.", "Set holds.", "That's the bit.", "Roast!", "Aisle!", "Work!", "SPECIAL!", "Good night."),
    { Q: "Cone of a bit.", W: "Dash the aisle.", E: "Taunt the room and raise a bit-shield.", R: "Charge the stage." },
  ),
  "maga-ricky": K(
    2, "fighter", "guard", "Yard",
    "Second Wind",
    "Under a third health the chair braces once.",
    "Rolls the line and holds the front.",
    "Short sentences. Stays in the scrum.",
    "A hard chalk line, dash behind a brace, a thicker brace when low, then stop and stun the first hero. He stays seated.",
    3.4, 5.8, 1.05, 5,
    V("Ricky. Yard's open.", "LAST BELL.", "Down in the yard.", "Yard holds.", "Stay there.", "Line!", "Cut!", "Chin!", "BELL!", "Again."),
    { Q: "Cone of a chalk line.", W: "Dash the gap.", E: "Brace in the chair.", R: "Charge and burst." },
  ),
  "maga-hooli": K(
    2, "marksman", "barrage", "Punk",
    "Punk Barrage",
    "Basic shots splash nearby rivals. A fifth of them bash. One passive — stun plus splash on the same hit.",
    "An aggressive ranged fighter who stacks rapid studs with punishing precision. Punk Barrage can stun the name he tagged while splashing the knot, and Sniper Shot deletes a priority from extreme range.",
    "Cocky, loud, first off the barrier.",
    "Keep range, stack shots, dive out, then the long stud.",
    1.6, 6.8, 0.88, 2,
    V("Hooli. Locked.", "SNIPER SHOT!", "Mohawk's down.", "Pit holds.", "Stay down.", "Stud!", "Dive!", "Encore!", "SNIPER!", "Oi!"),
    { Q: "Bolt a silver stud. Cashes into Punk Barrage.", W: "Dash the pit. Grants a short stride.", E: "Attack faster. The barrage speeds up.", R: "Sniper stance, then one long high-damage stud." },
  ),
  "maga-bushed": K(
    1, "tank", "guard", "Ranch",
    "Protection",
    "Low health raises a ranch shield once. The coalition holds.",
    "A reliable ranch tank who slows the map and soaks the street.",
    "Folksy, steady, misunderestimated on purpose.",
    "Stun and shove off the porch, shield the ranch, a pulsing slow that heals allies, then a late nova that shields them.",
    4.6, 5.4, 1.16, 8,
    V("Bushed. Mission.", "SURGE.", "Need a nap.", "Ranch holds.", "Resolved.", "Mission!", "Wall!", "Coalition!", "Surge!", "Yes."),
    { Q: "Stun the briefing.", W: "Ranch shield. Pairs with the low-health wall.", E: "Slow the map.", R: "Protect the lane. Drop the arch." },
  ),

  "lw-harass": K(
    2, "controller", "link", "Brief",
    "Word Salad",
    "Heals grow when the circle stays. The sentence never lands, the street does.",
    "A podium controller who laughs, slows, and keeps the tape.",
    "Bright, circular, always unburdened.",
    "A slow cone that heals allies, a hard line on the first body, a heal that pays again, then a double nova.",
    2.2, 8.6, 1.16, 5,
    V("Harass. Let's proceed.", "WORD SALAD!", "What can be, unburdened.", "Podium holds.", "Noted.", "Cackle!", "Brief!", "Unburdened!", "SALAD!", "I have a question."),
    { Q: "Cone of a laugh that holds the line.", W: "Slow a knot at the tape.", E: "Heal the circle. Stronger with allies.", R: "Nova the podium." },
  ),
  "lw-sandbags": K(
    1, "tank", "link", "Rally",
    "People Power",
    "Heals grow when the line is stacked. The people stand, the charge lands.",
    "A people's tank who taunts donors and heals the stoop.",
    "Hoarse, sincere, always mid-rally.",
    "Taunt and heal the line, pull a stun, heal twice when low, then a dash that shoves and heals allies.",
    4.2, 7.2, 1.12, 7,
    V("Sandbags. Enough is enough.", "FEEL THE BERN!", "Not me, us — I'm down.", "The people hold.", "Class dismissed.", "Rally!", "Class!", "Revolution!", "BERN!", "Medicare for this lane."),
    { Q: "Taunt rivals into the line.", W: "Stun the donor.", E: "Heal the nearby line. Stronger in a crowd.", R: "Charge, knocking the rival aside." },
  ),
  "lw-bitenten": K(
    1, "support", "link", "Unity",
    "Unity Link",
    "Heals grow when the basement is full. Dark Brandon lifts the room.",
    "A unity support who slows halls, shields, and ice-creams the line.",
    "Folksy, wandering, suddenly the basement glows.",
    "A hard slick that shoves, a late basement shield, heal the lowest ally, then a big heal that stuns heroes later.",
    3.8, 8.4, 1.12, 6,
    V("Biten. Come on, man.", "DARK BRANDON.", "I used to have a kit.", "Unity holds.", "Malarkey.", "Come on!", "Basement!", "Ice cream!", "BRANDON!", "Here's the deal."),
    { Q: "Slow a slick of the hall.", W: "Basement shield.", E: "Heal the nearby line. Stronger with friends.", R: "Big heal. Link the room. Stronger when stacked." },
  ),
  "lw-odramma": K(
    2, "mage", "link", "Hope",
    "Hope",
    "Heals grow on the aisle. Hope Dealer spends the room.",
    "A hope mage who bolts lines and novas the lawn.",
    "Smooth, lifted, always mid-sentence.",
    "A bolt that hastes allies, a late far slow, the next hit heals, then a nova that marks and heals allies.",
    2.0, 8.8, 1.16, 5,
    V("O'Drama. Yes we can.", "HOPE DEALER!", "That was the moment.", "Lawn holds.", "Fired up.", "Yes!", "Prompt!", "Fired!", "HOPE!", "Let me be clear."),
    { Q: "Bolt a hope line.", W: "Slow the floor.", E: "Heal the aisle. Stronger with a crowd.", R: "Nova the lawn. Large and loud." },
  ),
  "lw-youngturkey": K(
    2, "controller", "zone", "Crew",
    "The Crew",
    "Slows and rains leave the Crew on the tile. How Dare cashes a mark.",
    "A progressive crew that zones the lane instead of standing in it.",
    "Many voices, one desk, always mid-slogan.",
    "A hero slow that comes due, far rain twice, haste the squad, then a late stun bolt on heroes.",
    2.1, 8.8, 1.16, 5,
    V("Turkeys. Tax the lane.", "HOW DARE.", "The crew's out.", "Desk holds.", "Logged.", "Tax!", "Green!", "Care!", "DARE!", "Squad up."),
    { Q: "Slow a slogan zone. Leaves the Crew.", W: "Rain a crew on a point. Zone stays.", E: "Heal the circle.", R: "Bolt the feature. Cashes a Crew stamp." },
  ),
  "lw-hocking": K(
    3, "mage", "zone", "Horizon",
    "Event Horizon",
    "Slows and novas leave a well. The hole owns the tile after BLACK HOLE.",
    "A cosmic artillery mind who wells the lab, then folds it.",
    "Dry, vast, slightly amused by gravity.",
    "A hard well that pulls, blink and vanish, a beam that marks the first, then a late ring that pulls. He stays seated.",
    1.4, 9.6, 1.18, 5,
    V("Hocking. Brief history.", "BLACK HOLE.", "Hawking, but funnier.", "Lab holds.", "Collapsed.", "Well!", "Drift!", "Beam!", "HOLE!", "Obviously."),
    { Q: "Slow the lab into a well. Zone lingers.", W: "Dash a hop between frames.", E: "Bolt a brief history.", R: "Detonate the rack. Leaves a well." },
  ),
  "lw-vakxie": K(
    2, "support", "link", "Peer",
    "Peer Review",
    "Heals grow at the bench. Nationwide Protocol lifts a stacked room.",
    "A facts-matter support who doses, flattens, and reviews the lane.",
    "Calm, cited, always one paper ahead.",
    "A hard bolt that stuns a marked rival, a late slow line, cleanse and heal twice, then a ground heal that pays again.",
    2.2, 9.0, 1.16, 5,
    V("Vaxxie. The facts.", "NATIONWIDE PROTOCOL.", "Sample's lost.", "Bench holds.", "Reviewed.", "Dose!", "Flatten!", "Review!", "BOOST!", "Cited."),
    { Q: "Bolt a reagent. Analyze the rival.", W: "Slow a cloud of facts.", E: "Heal the bench. Stronger with peers.", R: "Big heal across the protocol. Stronger in a crowd." },
  ),
  "lw-climate": K(
    2, "controller", "zone", "Dome",
    "Weather Desk",
    "Rains and novas leave a dome. The map stays weather after 1.5 Degrees.",
    "A planet controller who stuns carbon and novas the hall.",
    "Urgent, green, always mid-briefing.",
    "Stun a far speaker, a hard dome that pops, rain that heals allies, then a double nova that shoves.",
    1.9, 8.8, 1.16, 5,
    V("Planet Defender. The desk is live.", "ONE POINT FIVE.", "The ice went.", "Hall holds.", "Logged.", "Carbon!", "Dome!", "Cover!", "1.5!", "The science."),
    { Q: "Stun a speaker.", W: "Slow the floor. Dome lingers.", E: "Rain plants. Zone stays.", R: "Nova the hall. Weather wins. Leaves a dome." },
  ),
  "lw-journalist": K(
    2, "marksman", "mark", "Source",
    "Source",
    "Slows set a Source. Exclusive cashes the leak.",
    "A ranged scout who bolts headlines and dashes the basement.",
    "Ink, haste, never names the Source.",
    "A far mark that shoves, slow heroes only, a backstep that hastes when low, then a late hard bolt if marked.",
    1.8, 7.4, 1.18, 3,
    V("Journalist. On background.", "EXCLUSIVE.", "Source burned.", "Copy holds.", "Printed.", "Leak!", "Check!", "Run!", "EXCLUSIVE!", "Off record."),
    { Q: "Bolt a headline. Cashes Source.", W: "Slow the copy and set Source.", E: "Dash the basement.", R: "Collect bolt. Spends the leak." },
  ),

  "wild-icon": K(
    2, "tank", "guard", "Icon",
    "Iconic Presence",
    "Low health raises a streetwear shield once. The lawn still has a body on it.",
    "Unclassified streetwear tank. Stomps pavement, then the rally.",
    "Quiet, heavy, dressed like a billboard.",
    "A close stun and shove, a decaying shield when low, a close hard slow, then a late taunt that shields allies.",
    4.4, 5.6, 1.14, 8,
    V("The Icon. On the lawn.", "THE RALLY.", "The fit ripped.", "Lawn holds.", "Iconic.", "Stomp!", "Will!", "Crowd!", "RALLY!", "Stay."),
    { Q: "Cone that stomps the pavement.", W: "Heavy streetwear shield. Pairs with the low-health pulse.", E: "Slow a knot of rivals.", R: "Teamfight nova. The lawn empties." },
  ),
  "wild-enigma": K(
    3, "controller", "haste", "File",
    "Hidden Connections",
    "Vanishing Act leaves file speed. The name never stays in frame.",
    "A dark-file controller who slows a name and leaves the shot.",
    "Soft voice, no face, always mid-redaction.",
    "Slow a marked name longer, vanish and blink late, shield twice, then a late pull-stun on heroes.",
    2.2, 8.6, 1.14, 5,
    V("The Enigma. Don't ask.", "THE DEEP END.", "Redacted.", "File holds.", "Closed.", "File!", "Gone!", "Life!", "DEEP!", "No comment."),
    { Q: "Slow a name on the book.", W: "Dash out of the frame. Grants file speed.", E: "File shield.", R: "Stun the last name on the list." },
  ),
  "wild-cartoons": K(
    3, "controller", "zone", "Gag",
    "Fourth Wall",
    "Rains and novas leave a gag on the tile. The cafeteria stays denied.",
    "A hazard duo that rains traps and cutaways through the gag.",
    "Two voices, one kit, no safety meeting.",
    "A trap that stuns the first body later, stun twice, blink far, then a double nova that shoves heroes.",
    2.4, 8.2, 1.1, 5,
    V("Cartoons. Don't look down.", "ABSURDITY!", "That's the gag.", "Lot holds.", "Cut.", "Trap!", "Trouble!", "Cutaway!", "ABSURD!", "To be continued."),
    { Q: "Rain a hazard. Zone stays.", W: "Stun the cafeteria.", E: "Dash through the gag.", R: "Nova the lot. Leaves a denied tile." },
  ),
  "wild-dynasty": K(
    3, "assassin", "haste", "Trend",
    "Trending",
    "Dashes leave trend speed. The feed is a route.",
    "A trending caster who flashes, novas, and walks off camera.",
    "Bright, brief, always mid-viral.",
    "A bolt that slows and shoves the one in frame, a small nova with haste, a dash that marks, then a late dash stun.",
    1.8, 7.0, 0.98, 2,
    V("Dynasty. Live.", "BREAK THE INTERNET!", "Unfollowed.", "Feed holds.", "Posted.", "Flash!", "Viral!", "Fame!", "BREAK!", "Like."),
    { Q: "Bolt a portrait.", W: "Nova the feed.", E: "Dash between frames. Grants trend speed.", R: "Charge and burst. Kill refunds Fame Dash." },
  ),
  "wild-legend": K(
    2, "fighter", "vamp", "Hook",
    "The Legend",
    "Hero hits pay a little health back. The bit never ends.",
    "A close-range disruptor who hooks a laugh and rolls through it.",
    "Uncomfortable, durable, always mid-bit.",
    "Hook and stun from the chair, hard-slow heroes, roll back behind a shield, then stop and shove twice. She stays seated.",
    3.4, 6.2, 1.06, 6,
    V("The Legend. Don't laugh.", "ABSOLUTE CHAOS!", "Tough room.", "Stage holds.", "That's the bit.", "Hook!", "Silence!", "Roll!", "CHAOS!", "Anyway."),
    { Q: "Stun the nearest laugh. Heals a sliver on heroes.", W: "Slow the room.", E: "Dash the last 100.", R: "Charge and burst." },
  ),
  "wild-karen": K(
    2, "tank", "tauntwall", "Manager",
    "I Want To Speak To Your Manager",
    "Taunt raises a manager shield. The counter soaks while you complain.",
    "A frontline taunt tank who forces the fight at the desk.",
    "Bright, furious, receipt in hand.",
    "Taunt and pull to the counter, a louder stun when low, a late shove on the first, then a nova that taunts and shields later.",
    4.3, 5.8, 1.12, 8,
    V("Entitlement. Excuse me.", "MANAGER SUMMONED!", "I want your supervisor.", "Counter holds.", "Refunded.", "Complaint!", "Demand!", "Excuse me!", "MANAGER!", "Unacceptable."),
    { Q: "Taunt the room and raise a manager shield.", W: "Stun the desk.", E: "Cone of a raised voice.", R: "Nova the counter." },
  ),
  "wild-vegan": K(
    2, "support", "link", "Root",
    "Plant Power",
    "Heals grow in the vines. A stacked circle eats better.",
    "A nature desk that roots, heals, and hops the map.",
    "Gentle, certain, will vine your ankles.",
    "Close vines pull, the next hit heals an ally, a dash leaves a slow line, then late rain that heals allies.",
    2.3, 8.8, 1.14, 5,
    V("Plant Power. Grow.", "PLANETARY HARVEST.", "Composted.", "Garden holds.", "Rooted.", "Sprout!", "Vigor!", "Wave!", "HARVEST!", "Namaste, but mean."),
    { Q: "Slow a knot in vines.", W: "Heal the circle. Stronger with friends.", E: "Dash a hop across the map.", R: "Rain plants on a point." },
  ),
  "wild-butter": K(
    3, "mage", "zone", "Patch",
    "Beta Build",
    "Rains and novas leave a patch slow. The rack stays denied.",
    "Gadget artillery that rains drones and overrides the lane.",
    "Nerdy, live, always one patch from stable.",
    "Gadgets hit twice and mark, a laser on the first body, speed while low that pops, then a late slow nova.",
    1.5, 9.5, 1.16, 4,
    V("The Tech. Deploying.", "SYSTEM OVERRIDE.", "Rollback.", "Rack holds.", "Shipped.", "Drones!", "Laser!", "Patch!", "OVERRIDE!", "It's a feature."),
    { Q: "Rain gadgets. Zone stays.", W: "Bolt a gadget.", E: "Attack faster. Rearm the kit.", R: "Nova the rack. Leaves a hang." },
  ),
  "wild-bruella": K(
    3, "fighter", "rage", "Chaos",
    "Chaos Energy",
    "Low health is the other self. Swings speed up when the coat tears.",
    "A chaos fighter who cones, copies, and melts down through the lane.",
    "Unstable, grinning, sides optional.",
    "Chaos cone, mirror dash, stun, total-meltdown charge.",
    3.0, 6.2, 1.0, 5,
    V("Bruella. Pick a side.", "TOTAL MELTDOWN!", "Which one died?", "Lane holds.", "Both of us.", "Chaos!", "Mirror!", "Wait—", "MELTDOWN!", "Oops."),
    { Q: "Cone of a random swing.", W: "Dash a copy through the lane.", E: "Stun the briefing.", R: "Charge and burst." },
  ),
  "wild-danny": K(
    3, "assassin", "ambush", "Who",
    "Who Is Danny?",
    "First hit after Disappear is the ambush. Woods make him nobody.",
    "An assassin who stuns from nowhere and leaves the tunnel.",
    "Blank, polite, already behind you.",
    "Mystery stun, disappear dash, unknown aspd, who-saw-that charge.",
    1.9, 5.8, 0.96, 2,
    V("Danny. Who?", "WHO SAW THAT?", "Nobody.", "Gone.", "Who?", "Now.", "Gone.", "Unknown.", "SAW THAT?", "Hi."),
    { Q: "Stun from nowhere. Lands after Disappear.", W: "Dash the tunnels. Arms the ambush.", E: "Attack faster after the vanish.", R: "Charge the ambush. Kill refunds Disappear." },
  ),
  "wild-price": K(
    3, "marksman", "heat", "????",
    "Unknown",
    "Spells stack ????. At five, the window lengthens. The unlabeled ult spends it.",
    "A time carry who steps a frame ahead and never books the window.",
    "Unlabeled, punctual, slightly wrong century.",
    "Time-step dash, glitch stun, unidentified slow, ???? nova.",
    2.2, 6.6, 1.02, 3,
    V("Price. ????", "????", "Window closed.", "???? holds.", "????", "Step.", "Glitch.", "Who?", "????", "Now."),
    { Q: "Dash a frame ahead. Builds ????.", W: "Stun the clock. Builds ????.", E: "Slow feet in wet time. Builds ????.", R: "Spends ????. Nobody booked this window." },
  ),
  "wild-cezanne": K(
    2, "controller", "zone", "Study",
    "Artistic Vision",
    "Rains and novas leave pigment. The lane stays painted.",
    "A paint controller who marks, slows, and exhibits the chamber.",
    "Soft, exact, will ruin your shoes.",
    "A slowing pigment bolt, a slow stroke, rain that marks later, then a nova that marks again. The lollipop swing stays.",
    1.8, 8.8, 1.16, 5,
    V("Pheobe. Still life.", "FINAL EXHIBITION.", "The light went.", "Chamber holds.", "Sold.", "Splash!", "Stroke!", "Master!", "SHOW!", "Don't touch."),
    { Q: "Bolt a study.", W: "Slow the panel. Pigment lingers.", E: "Rain pigment. Zone stays.", R: "Nova the chamber. Leaves the show." },
  ),
  "wild-metalpak": K(
    2, "marksman", "heat", "Volume",
    "Full Volume",
    "Bursts stack Volume. Five stacks reach farther. Massive Solo spends the drop.",
    "A ranged gadget carry who cones iron and solos the point.",
    "Loud, sincere, always one riff from a wipe.",
    "Metal cone, amplifier aspd, riff bolt, massive-solo rain.",
    2.3, 6.8, 1.14, 3,
    V("MetalPak. Volume up.", "MASSIVE SOLO!", "Feedback.", "Stage holds.", "Encore.", "Burst!", "Amp!", "Riff!", "SOLO!", "One two."),
    { Q: "Cone of iron. Stacks Volume.", W: "Attack faster. Builds Volume.", E: "Bolt a rocket. Builds Volume.", R: "Rain the drop. Spends Volume." },
  ),
  "wild-hatty": K(
    2, "marksman", "haste", "Walk",
    "Signature Style",
    "Catwalk leaves walk speed. The rail is the lane.",
    "A runway marksman who throws brims and never walks straight.",
    "Bright, vain, always mid-turn.",
    "Hat bolt, fashion aspd, catwalk dash, main-character charge.",
    1.9, 6.4, 1.12, 2,
    V("HattyHats. Look.", "MAIN CHARACTER.", "The hat fell.", "Runway holds.", "Iconic.", "Throw!", "Flash!", "Walk!", "MAIN!", "Thanks, hats."),
    { Q: "Bolt a brim.", W: "Attack faster.", E: "Dash the rail. Grants walk speed.", R: "Charge the bowl. Kill refunds the walk." },
  ),
  "wild-octo": K(
    2, "tank", "zone", "Limb",
    "????",
    "Slows and novas leave a limb on the tile. Intentionally unexplained.",
    "A multi-limb tank that grabs, cones, and novas the strangest fight.",
    "Wet, confused, too many arms.",
    "Tentacle stun, octo-grab slow, what-is-that cone, octopus nova.",
    4.2, 5.8, 1.14, 8,
    V("Octo. ????", "OCTOPUS MODE.", "Ink.", "???? holds.", "Grabbed.", "Limb.", "Grab.", "What?", "MODE.", "Blub."),
    { Q: "Stun a limb on the lane.", W: "Slow a cloud of arms. Zone lingers.", E: "Cone of a question.", R: "Nova. The strangest teamfight. Leaves a limb." },
  ),
  "mma-macgregor": K(
    3, "assassin", "ambush", "Notorious",
    "Notorious",
    "A dash marks the next punch. Woods make that punch cleaner. Left Hand still loads its own cone.",
    "A southpaw assassin who talks first and finishes with the straight left.",
    "Loud, precise, already celebrating.",
    "The next punch adds a cone, taunt heroes, stun behind a small shield, then stop and load the finish.",
    2.0, 6.0, 0.96, 3,
    V("Macgregor. Notorious.", "PRECISION FINISH!", "The left missed.", "The octagon holds.", "That's the one.", "Left!", "Smack!", "Counter!", "FINISH!", "Who's next?"),
    { Q: "Straight left cone. Arms the Notorious hit after a dash.", W: "Taunt the cage. They have to look.", E: "Stun the swing that missed.", R: "Charge and burst. Kill refunds the dash." },
  ),
  "mma-nurmagoat": K(
    2, "fighter", "vamp", "Sambo",
    "Undefeated Energy",
    "Hero hits pay a sliver back. The grind never ends.",
    "A grappler who takes the lane to the mat and keeps it there.",
    "Calm, heavy, already on top.",
    "Hook and stun onto the mat, a close hard pulse, taunt and shove, then a nova that pulls and stuns.",
    3.8, 5.8, 1.08, 6,
    V("Nurmagoat. Send location.", "NO ESCAPE.", "The mat's mine.", "Eagle still flies.", "Tap.", "Down!", "Control!", "Fence!", "ESCAPE!", "Sambo."),
    { Q: "Stun. The takedown starts the grind.", W: "Slow a knot. Ground control.", E: "Taunt into the fence.", R: "Nova. The cage closes." },
  ),
  "mma-jonesy": K(
    2, "fighter", "heat", "Reach",
    "Reach Advantage",
    "Elbows and IQ stack Reach. At five, the swing lengthens. Champion's Round spends it.",
    "A long-reach fighter who switches stance and owns the fifth.",
    "Loose, tall, always a step outside.",
    "A far elbow that shoves, a dash that shoves the near, speed and a marked next swing, then a late knock louder when low.",
    3.2, 6.2, 1.02, 5,
    V("Jonesy. Bones.", "CHAMPION'S ROUND.", "The reach lost.", "Title holds.", "Next.", "Elbow!", "Spin!", "IQ!", "ROUND!", "Easy."),
    { Q: "Long cone. Stacks Reach.", W: "Dash the stance switch. Builds Reach.", E: "Attack faster. Builds Reach.", R: "Spends Reach on the cage nova." },
  ),
  "mma-adesanyaish": K(
    3, "assassin", "mark", "Feint",
    "Stylebender",
    "Distance Control stamps a Feint. The next bolt is the real one.",
    "A stylist who feints, steps, and cashes the counter in the pocket.",
    "Tall, theatrical, never in the pocket you wanted.",
    "A jab that marks and pays on the mark, a far slow shove, a backstep if marked, then a late stun bolt if marked.",
    1.9, 7.0, 1.14, 3,
    V("Adesanya-ish. Style.", "LAST STYLE STANDING.", "The angle died.", "The pocket holds.", "Point.", "Feint!", "Distance!", "Step!", "STYLE!", "Beautiful."),
    { Q: "Bolt a jab that isn't the jab. Cashes Feint.", W: "Slow the pocket and stamp Feint.", E: "Dash the angle.", R: "Collect bolt. Spends the feint." },
  ),
  "mma-poirierish": K(
    2, "fighter", "rage", "Diamond",
    "Diamond Will",
    "Under 40% health the pocket speeds up. Comebacks land.",
    "A pocket boxer who gets meaner when the diamond cracks.",
    "Friendly, heavy-handed, never done.",
    "A cone that hits twice, a close stun, a decaying shell thicker when low, then a nova and a boon when low.",
    3.4, 6.0, 1.02, 5,
    V("Poirier-ish. Diamond.", "DIAMOND COMEBACK!", "I'm still here.", "Pocket holds.", "Liver.", "Combo!", "Body!", "Hard!", "COMEBACK!", "Let's go."),
    { Q: "Cone of the pocket boxing.", W: "Stun the liver.", E: "Diamond shield. Buy the comeback.", R: "Nova. Low health hits harder." },
  ),
  "mma-diazish": K(
    1, "tank", "tauntwall", "Stockton",
    "Stockton Energy",
    "Come At Me raises a tape shield. Never Tired grows if the room stays.",
    "A Stockton grinder who talks, jabs, and outlasts the fifth.",
    "Loose, grinning, already in round five.",
    "A close slow cone, a taunt-shield that taunts again, a heal that pays again if still low, then a double nova that heals when low.",
    4.0, 6.4, 1.1, 6,
    V("Diaz-ish. Stockton.", "FIVE ROUND WAR.", "Still standing.", "The fifth holds.", "Who's next?", "Pressure!", "Come!", "Cardio!", "WAR!", "Yeah."),
    { Q: "Cone of the long jab.", W: "Taunt and raise a tape shield.", E: "Heal the cardio. Stronger with friends.", R: "Nova the late fight." },
  ),
  "wild-airosoul": K(
    2, "support", "link", "Vibe",
    "Good Vibes",
    "Heals grow on the link. Ascension lifts a stacked booth.",
    "A mobility support that orbs, links, and floats the key change.",
    "Soft, floaty, will save you and leave.",
    "Soul bolt, vibe heal, float hop, ascension nova.",
    2.2, 8.8, 1.14, 5,
    V("Airosoul. Breathe.", "ASCENSION.", "The vibe broke.", "Booth holds.", "Lifted.", "Orb.", "Link.", "Float.", "UP.", "Mmm."),
    { Q: "Bolt the request line.", W: "Heal the listeners. Stronger on a link.", E: "Dash a hop between frames.", R: "Nova the booth." },
  ),
  "wild-slush": K(
    2, "marksman", "haste", "Powder",
    "Powder",
    "A takedown refunds the first two tricks. A dash leaves fresh tracks.",
    "A half-size winter scout who packs snow and throws it.",
    "Short, cheerful, already winding up.",
    "A close slow bolt, a late drift, a haste, then a late shove.",
    2.0, 7.2, 1.12, 3,
    V("Sgt. Slush. Packed.", "AVALANCHE!", "Melted.", "The fort holds.", "Lump.", "Lump!", "Drift!", "Tracks!", "AVALANCHE!", "Cold."),
    { Q: "Slow a rival already in the pocket.", W: "A drift that pins feet.", E: "Move faster on fresh snow.", R: "The hill comes down and shoves." },
  ),
};

export function kitPatch(id: string): KitPatch {
  return KITS[id] ?? FALLBACK;
}

export function diffStars(n: Difficulty): string {
  return n === 1 ? "★☆☆" : n === 2 ? "★★☆" : "★★★";
}

export function diffLabel(n: Difficulty): string {
  return n === 1 ? "Easy" : n === 2 ? "Medium" : "Hard";
}

export function bandLabel(band: RoleBand): string {
  if (band === "tank") return "Tank";
  if (band === "fighter") return "Fighter";
  if (band === "assassin") return "Assassin";
  if (band === "mage") return "Mage";
  if (band === "marksman") return "Marksman";
  if (band === "support") return "Support";
  return "Controller";
}

export function sealHero(h: HeroDef): HeroDef {
  const k = kitPatch(h.id);
  const abilities = h.abilities.map((ab) => ({
    ...ab,
    blurb: ab.mech ? ab.blurb : (k.blurbs?.[ab.key] ?? ab.blurb),
  }));
  const voice = h.wing === "maga" ? { ...k.voice, death: MAGA_DEATH } : k.voice;
  return {
    ...h,
    abilities,
    passive: k.passive,
    difficulty: k.difficulty,
    bio: k.bio,
    personality: k.personality,
    style: k.style,
    hpRegen: k.hpRegen,
    manaRegen: k.manaRegen,
    aspd: k.aspd,
    mr: k.mr,
    kind: k.kind,
    band: k.band,
    stack: k.stack,
    voice,
  };
}
