import { liveHeroId as liveId } from "./heroes.ts";

/** Shared C42 kit bible: colors, hair, body, prop, gait. Pixel painter reads these. Heroes only. */

export type HairStyle =
  | "sweep"
  | "slick"
  | "short"
  | "dark"
  | "mess"
  | "locks"
  | "fade"
  | "prof"
  | "white"
  | "close"
  | "bob"
  | "thin"
  | "duo"
  | "lab"
  | "curl"
  | "hood"
  | "mask"
  | "mascot"
  | "glam"
  | "beard"
  | "blondbob"
  | "visor"
  | "beret"
  | "buzz"
  | "goat"
  | "crest"
  | "slickblond"
  | "longish";

export type BodyStyle =
  | "oversuit"
  | "tech"
  | "hoodie"
  | "broadcast"
  | "tory"
  | "robe"
  | "drip"
  | "blazer"
  | "navy"
  | "parka"
  | "hope"
  | "gown"
  | "chair"
  | "desk"
  | "labcoat"
  | "earth"
  | "street"
  | "cloak"
  | "toon"
  | "pink"
  | "gold"
  | "pearl"
  | "gadget"
  | "paint"
  | "shorts";

export type PropStyle =
  | "tie"
  | "rocket"
  | "mic"
  | "megaphone"
  | "book"
  | "mittens"
  | "halo"
  | "flask"
  | "globe"
  | "glove"
  | "sash"
  | "belt"
  | "staff"
  | "tape"
  | "camera"
  | "file"
  | "brush"
  | "stud"
  | "none";

export type Gait =
  | "waddle"
  | "bounce"
  | "glide"
  | "stomp"
  | "roll"
  | "swagger"
  | "shuffle"
  | "fight"
  | "saunter"
  | "march"
  | "talk"
  | "duo";

export type PixelKit = {
  id: string;
  skin: string;
  skinHi: string;
  hair: string;
  hairHi: string;
  coat: string;
  coatHi: string;
  coatLo: string;
  accent: string;
  trim: string;
  hairStyle: HairStyle;
  body: BodyStyle;
  prop: PropStyle;
  vfx: string;
  gait: Gait;
  wide?: boolean;
};

const MAGA = "#c9a24a";
const SEA = "#3ec8c1";
const WILD = "#c8c2b4";
const MMA = "#efe6d6";

export const PIXEL_KITS: Record<string, PixelKit> = {
  "maga-grumptor": {
    id: "maga-grumptor",
    skin: "#f0b48a",
    skinHi: "#f8d4b4",
    hair: "#f0c83a",
    hairHi: "#ffe566",
    coat: "#1a3d9c",
    coatHi: "#2d5ad4",
    coatLo: "#0e2468",
    accent: "#d4121c",
    trim: MAGA,
    hairStyle: "sweep",
    body: "navy",
    prop: "tie",
    vfx: "#d4121c",
    gait: "swagger",
    wide: true,
  },
  "maga-elonmolk": {
    id: "maga-elonmolk",
    skin: "#f5e0c3",
    skinHi: "#fff6e4",
    hair: "#1a120c",
    hairHi: "#3a2a20",
    coat: "#cfd8dc",
    coatHi: "#eef4f6",
    coatLo: "#6a767c",
    accent: "#69f0ae",
    trim: MAGA,
    hairStyle: "slick",
    body: "tech",
    prop: "rocket",
    vfx: "#69f0ae",
    gait: "march",
  },
  "maga-rogentor": {
    id: "maga-rogentor",
    skin: "#d4a574",
    skinHi: "#e8c49a",
    hair: "#3a2418",
    hairHi: "#5c3a28",
    coat: "#4a3a28",
    coatHi: "#6a5a40",
    coatLo: "#2a1c12",
    accent: "#c9a24a",
    trim: MAGA,
    hairStyle: "short",
    body: "hoodie",
    prop: "mic",
    vfx: "#c9a24a",
    gait: "bounce",
  },
  "maga-alexgroans": {
    id: "maga-alexgroans",
    skin: "#e8b896",
    skinHi: "#f6d0b4",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#3a2418",
    coatHi: "#5a3a28",
    coatLo: "#1a1008",
    accent: "#e07a3d",
    trim: MAGA,
    hairStyle: "dark",
    body: "broadcast",
    prop: "megaphone",
    vfx: "#e07a3d",
    gait: "stomp",
  },
  "maga-boris": {
    id: "maga-boris",
    skin: "#f3d2b5",
    skinHi: "#fff1dc",
    hair: "#f0e4b8",
    hairHi: "#fff8dc",
    coat: "#3d6ea6",
    coatHi: "#6a96c4",
    coatLo: "#1a3a5c",
    accent: "#c4161c",
    trim: MAGA,
    hairStyle: "mess",
    body: "tory",
    prop: "book",
    vfx: "#3d6ea6",
    gait: "shuffle",
    wide: true,
  },
  "maga-brander": {
    id: "maga-brander",
    skin: "#d4a574",
    skinHi: "#e8c49a",
    hair: "#3a2418",
    hairHi: "#5c3a28",
    coat: "#b08968",
    coatHi: "#d4b090",
    coatLo: "#6a4a30",
    accent: "#c9a24a",
    trim: MAGA,
    hairStyle: "locks",
    body: "robe",
    prop: "mic",
    vfx: "#b08968",
    gait: "saunter",
  },
  "maga-vestyt": {
    id: "maga-vestyt",
    skin: "#8d5524",
    skinHi: "#b07a40",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#efe6d6",
    coatHi: "#fffaf0",
    coatLo: "#8a8070",
    accent: "#5c3317",
    trim: MAGA,
    hairStyle: "fade",
    body: "drip",
    prop: "none",
    vfx: "#efe6d6",
    gait: "swagger",
    wide: true,
  },
  "maga-quirk": {
    id: "maga-quirk",
    skin: "#e8b896",
    skinHi: "#f6d0b4",
    hair: "#3a2418",
    hairHi: "#5c3a28",
    coat: "#1e3a6e",
    coatHi: "#3a5a9c",
    coatLo: "#102040",
    accent: "#c4a86a",
    trim: MAGA,
    hairStyle: "short",
    body: "blazer",
    prop: "mic",
    vfx: "#f0c14a",
    gait: "bounce",
  },
  "maga-tommy": {
    id: "maga-tommy",
    skin: "#e8b896",
    skinHi: "#f6d0b4",
    hair: "#3a2418",
    hairHi: "#5c3a28",
    coat: "#1a4a9c",
    coatHi: "#3a6acc",
    coatLo: "#0c2460",
    accent: "#8a4030",
    trim: MAGA,
    hairStyle: "short",
    body: "navy",
    prop: "mic",
    vfx: "#8a4030",
    gait: "stomp",
  },
  "maga-bushed": {
    id: "maga-bushed",
    skin: "#e8b896",
    skinHi: "#f6d0b4",
    hair: "#8a7a68",
    hairHi: "#b0a090",
    coat: "#1a2a6a",
    coatHi: "#3a4a8a",
    coatLo: "#0c1848",
    accent: "#c4161c",
    trim: MAGA,
    hairStyle: "short",
    body: "navy",
    prop: "mic",
    vfx: "#6b4a2a",
    gait: "shuffle",
    wide: true,
  },
  "maga-steers": {
    id: "maga-steers",
    skin: "#f3d2b5",
    skinHi: "#fff1dc",
    hair: "#2a1c12",
    hairHi: "#4a3020",
    coat: "#d4af37",
    coatHi: "#f0d070",
    coatLo: "#8a6a18",
    accent: "#efe6d6",
    trim: MAGA,
    hairStyle: "prof",
    body: "blazer",
    prop: "book",
    vfx: "#d4af37",
    gait: "talk",
  },
  "maga-ricky": {
    id: "maga-ricky",
    skin: "#fdc19e",
    skinHi: "#f7af89",
    hair: "#362024",
    hairHi: "#523f4a",
    coat: "#f1effc",
    coatHi: "#ffffff",
    coatLo: "#4d4b60",
    accent: "#2c2b3b",
    trim: MAGA,
    hairStyle: "curl",
    body: "chair",
    prop: "none",
    vfx: "#c45c2a",
    gait: "roll",
    wide: true,
  },
  "maga-hooli": {
    id: "maga-hooli",
    skin: "#e8b898",
    skinHi: "#f4d0b0",
    hair: "#ff2d8a",
    hairHi: "#ff7ab8",
    coat: "#241c16",
    coatHi: "#4a4034",
    coatLo: "#100c0a",
    accent: "#c8c4bc",
    trim: MAGA,
    hairStyle: "crest",
    body: "street",
    prop: "stud",
    vfx: "#ff4da6",
    gait: "swagger",
  },
  "lw-bitenten": {
    id: "lw-bitenten",
    skin: "#f3d2b5",
    skinHi: "#fff1dc",
    hair: "#efe6d6",
    hairHi: "#fffaf0",
    coat: "#2a3a58",
    coatHi: "#4a5a78",
    coatLo: "#141828",
    accent: "#7ec8ff",
    trim: SEA,
    hairStyle: "white",
    body: "navy",
    prop: "tie",
    vfx: "#7ec8ff",
    gait: "shuffle",
    wide: true,
  },
  "lw-sandbags": {
    id: "lw-sandbags",
    skin: "#f5e0c3",
    skinHi: "#fff6e4",
    hair: "#efe6d6",
    hairHi: "#fffaf0",
    coat: "#3ec8c1",
    coatHi: "#7ae8e0",
    coatLo: "#1a6a68",
    accent: "#c4161c",
    trim: SEA,
    hairStyle: "white",
    body: "parka",
    prop: "mittens",
    vfx: "#3ec8c1",
    gait: "stomp",
    wide: true,
  },
  "lw-odramma": {
    id: "lw-odramma",
    skin: "#5c3317",
    skinHi: "#8d5524",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#3d6ea6",
    coatHi: "#6a96c4",
    coatLo: "#1a3a5c",
    accent: "#c9a24a",
    trim: SEA,
    hairStyle: "close",
    body: "hope",
    prop: "halo",
    vfx: "#ffe08a",
    gait: "glide",
  },
  "lw-harass": {
    id: "lw-harass",
    skin: "#c68642",
    skinHi: "#d4a574",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#a78bfa",
    coatHi: "#c8b4ff",
    coatLo: "#5a3a9a",
    accent: "#c9a24a",
    trim: SEA,
    hairStyle: "bob",
    body: "gown",
    prop: "book",
    vfx: "#a78bfa",
    gait: "glide",
  },
  "lw-hocking": {
    id: "lw-hocking",
    skin: "#f3d2b5",
    skinHi: "#fff1dc",
    hair: "#c4b49a",
    hairHi: "#efe6d6",
    coat: "#2a2430",
    coatHi: "#4a4450",
    coatLo: "#141018",
    accent: "#7ec8ff",
    trim: SEA,
    hairStyle: "thin",
    body: "chair",
    prop: "halo",
    vfx: "#7ec8ff",
    gait: "roll",
    wide: true,
  },
  "lw-youngturkey": {
    id: "lw-youngturkey",
    skin: "#f5e0c3",
    skinHi: "#fff6e4",
    hair: "#2a1c12",
    hairHi: "#4a3020",
    coat: "#69f0ae",
    coatHi: "#a8ffd0",
    coatLo: "#2a8a58",
    accent: "#1a120c",
    trim: SEA,
    hairStyle: "duo",
    body: "desk",
    prop: "mic",
    vfx: "#69f0ae",
    gait: "duo",
    wide: true,
  },
  "lw-vakxie": {
    id: "lw-vakxie",
    skin: "#f5e0c3",
    skinHi: "#fff6e4",
    hair: "#8d5524",
    hairHi: "#b07a40",
    coat: "#efe6d6",
    coatHi: "#fffaf0",
    coatLo: "#8a8070",
    accent: "#5ad45a",
    trim: SEA,
    hairStyle: "lab",
    body: "labcoat",
    prop: "flask",
    vfx: "#5ad45a",
    gait: "march",
  },
  "lw-climate": {
    id: "lw-climate",
    skin: "#d4a574",
    skinHi: "#e8c49a",
    hair: "#3a2418",
    hairHi: "#5c3a28",
    coat: "#2a6a58",
    coatHi: "#4a9a80",
    coatLo: "#143828",
    accent: "#5ad45a",
    trim: SEA,
    hairStyle: "curl",
    body: "earth",
    prop: "globe",
    vfx: "#5ad45a",
    gait: "bounce",
  },
  "lw-journalist": {
    id: "lw-journalist",
    skin: "#e8b896",
    skinHi: "#f6d0b4",
    hair: "#3a2418",
    hairHi: "#5c3a28",
    coat: "#1a2a6a",
    coatHi: "#3a4a9a",
    coatLo: "#0c1848",
    accent: "#c4161c",
    trim: SEA,
    hairStyle: "longish",
    body: "blazer",
    prop: "mic",
    vfx: "#eceff1",
    gait: "talk",
  },
  "wild-icon": {
    id: "wild-icon",
    skin: "#5c3317",
    skinHi: "#8d5524",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#c45c5c",
    coatHi: "#e08080",
    coatLo: "#6a2020",
    accent: "#efe6d6",
    trim: WILD,
    hairStyle: "hood",
    body: "street",
    prop: "none",
    vfx: "#c45c5c",
    gait: "stomp",
    wide: true,
  },
  "wild-enigma": {
    id: "wild-enigma",
    skin: "#e8b896",
    skinHi: "#f6d0b4",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#3a3a48",
    coatHi: "#5a5a68",
    coatLo: "#1a1a24",
    accent: "#c9a24a",
    trim: WILD,
    hairStyle: "mask",
    body: "cloak",
    prop: "file",
    vfx: "#8a8490",
    gait: "glide",
  },
  "wild-cartoons": {
    id: "wild-cartoons",
    skin: "#f3d2b5",
    skinHi: "#fff1dc",
    hair: "#efe6d6",
    hairHi: "#fffaf0",
    coat: "#c4161c",
    coatHi: "#e05050",
    coatLo: "#6a1010",
    accent: "#e07a3d",
    trim: WILD,
    hairStyle: "mascot",
    body: "toon",
    prop: "none",
    vfx: "#e07a3d",
    gait: "duo",
    wide: true,
  },
  "wild-dynasty": {
    id: "wild-dynasty",
    skin: "#e8b896",
    skinHi: "#f6d0b4",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#ff6fae",
    coatHi: "#ffb0d0",
    coatLo: "#8a3060",
    accent: "#ffe08a",
    trim: WILD,
    hairStyle: "glam",
    body: "pink",
    prop: "camera",
    vfx: "#ff6fae",
    gait: "saunter",
  },
  "wild-legend": {
    id: "wild-legend",
    skin: "#e8b896",
    skinHi: "#f6d0b4",
    hair: "#3a2418",
    hairHi: "#5c3a28",
    coat: "#efe6d6",
    coatHi: "#fff6e4",
    coatLo: "#b8b0a4",
    accent: "#3a3e44",
    trim: WILD,
    hairStyle: "short",
    body: "chair",
    prop: "none",
    vfx: "#c9a24a",
    gait: "roll",
  },
  "wild-karen": {
    id: "wild-karen",
    skin: "#f3d2b5",
    skinHi: "#fff1dc",
    hair: "#efe6d6",
    hairHi: "#fffaf0",
    coat: "#c9a24a",
    coatHi: "#e8c878",
    coatLo: "#6a5420",
    accent: "#c4161c",
    trim: WILD,
    hairStyle: "blondbob",
    body: "pearl",
    prop: "book",
    vfx: "#c9a24a",
    gait: "stomp",
  },
  "wild-vegan": {
    id: "wild-vegan",
    skin: "#e8b070",
    skinHi: "#f0c090",
    hair: "#6a3a20",
    hairHi: "#8a5a38",
    coat: "#2a8a48",
    coatHi: "#5ad45a",
    coatLo: "#145028",
    accent: "#5ad45a",
    trim: WILD,
    hairStyle: "mess",
    body: "earth",
    prop: "globe",
    vfx: "#5ad45a",
    gait: "saunter",
  },
  "wild-butter": {
    id: "wild-butter",
    skin: "#f5e0c3",
    skinHi: "#fff6e4",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#2a2430",
    coatHi: "#4a4450",
    coatLo: "#141018",
    accent: "#69f0ae",
    trim: WILD,
    hairStyle: "visor",
    body: "gadget",
    prop: "rocket",
    vfx: "#69f0ae",
    gait: "march",
  },
  "wild-slush": {
    id: "wild-slush",
    skin: "#f6c7a4",
    skinHi: "#ffe3c4",
    hair: "#4a3020",
    hairHi: "#6a4830",
    coat: "#3f6b34",
    coatHi: "#6d9454",
    coatLo: "#6a4328",
    accent: "#6a4328",
    trim: "#c2a36a",
    hairStyle: "short",
    body: "parka",
    prop: "none",
    vfx: "#d7eef8",
    gait: "bounce",
  },
  "wild-cezanne": {
    id: "wild-cezanne",
    skin: "#f3d2b5",
    skinHi: "#fff1dc",
    hair: "#efe6d6",
    hairHi: "#fffaf0",
    coat: "#ce93d8",
    coatHi: "#e8c0f0",
    coatLo: "#6a3a78",
    accent: "#c9a24a",
    trim: WILD,
    hairStyle: "beret",
    body: "paint",
    prop: "brush",
    vfx: "#ce93d8",
    gait: "saunter",
  },
  "mma-macgregor": {
    id: "mma-macgregor",
    skin: "#f3d2b5",
    skinHi: "#fff1dc",
    hair: "#f0d070",
    hairHi: "#fff0b0",
    coat: "#1b6b3a",
    coatHi: "#3a9a58",
    coatLo: "#0c3a1c",
    accent: "#c9a24a",
    trim: MMA,
    hairStyle: "slickblond",
    body: "shorts",
    prop: "glove",
    vfx: "#1b6b3a",
    gait: "fight",
  },
  "mma-nurmagoat": {
    id: "mma-nurmagoat",
    skin: "#d4a574",
    skinHi: "#e8c49a",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#c4161c",
    coatHi: "#e05050",
    coatLo: "#6a1010",
    accent: "#efe6d6",
    trim: MMA,
    hairStyle: "goat",
    body: "shorts",
    prop: "sash",
    vfx: "#c4161c",
    gait: "stomp",
  },
  "mma-jonesy": {
    id: "mma-jonesy",
    skin: "#5c3317",
    skinHi: "#8d5524",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#c9a24a",
    coatHi: "#e8c878",
    coatLo: "#6a5420",
    accent: "#1a120c",
    trim: MMA,
    hairStyle: "buzz",
    body: "shorts",
    prop: "belt",
    vfx: "#c9a24a",
    gait: "swagger",
  },
  "mma-adesanyaish": {
    id: "mma-adesanyaish",
    skin: "#5c3317",
    skinHi: "#8d5524",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#5c7a4a",
    coatHi: "#8aaa70",
    coatLo: "#2a3a20",
    accent: "#efe6d6",
    trim: MMA,
    hairStyle: "crest",
    body: "shorts",
    prop: "glove",
    vfx: "#5c7a4a",
    gait: "saunter",
  },
  "mma-poirierish": {
    id: "mma-poirierish",
    skin: "#c68642",
    skinHi: "#d4a574",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#c4b49a",
    coatHi: "#e0d4bc",
    coatLo: "#6a5a40",
    accent: "#c4161c",
    trim: MMA,
    hairStyle: "short",
    body: "shorts",
    prop: "glove",
    vfx: "#c4b49a",
    gait: "fight",
  },
  "mma-diazish": {
    id: "mma-diazish",
    skin: "#c68642",
    skinHi: "#d4a574",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#2aa198",
    coatHi: "#5ad4c8",
    coatLo: "#145850",
    accent: "#efe6d6",
    trim: MMA,
    hairStyle: "longish",
    body: "shorts",
    prop: "tape",
    vfx: "#2aa198",
    gait: "swagger",
  },
};

export function pixelKit(rawId: string): PixelKit {
  const id = PIXEL_KITS[rawId] ? rawId : liveId(rawId);
  return PIXEL_KITS[id] ?? {
    id,
    skin: "#f3d2b5",
    skinHi: "#fff1dc",
    hair: "#1a120c",
    hairHi: "#3a2418",
    coat: "#6a4a30",
    coatHi: "#8a6a48",
    coatLo: "#3a2818",
    accent: MAGA,
    trim: MAGA,
    hairStyle: "short",
    body: "oversuit",
    prop: "none",
    vfx: MAGA,
    gait: "march",
  };
}
