import { BITEN_H, BITEN_PAL, BITEN_PIX, BITEN_W } from "./bitenSheet";
import { BORIS_H, BORIS_PAL, BORIS_PIX, BORIS_W } from "./borisSheet";
import { BUTTER_H, BUTTER_PAL, BUTTER_PIX, BUTTER_W } from "./butterSheet";
import { CARTOONS_H, CARTOONS_PAL, CARTOONS_PIX, CARTOONS_W } from "./cartoonsSheet";
import { CLIMATE_H, CLIMATE_PAL, CLIMATE_PIX, CLIMATE_W } from "./climateSheet";
import { DYNASTY_H, DYNASTY_PAL, DYNASTY_PIX, DYNASTY_W } from "./dynastySheet";
import { ENIGMA_H, ENIGMA_PAL, ENIGMA_PIX, ENIGMA_W } from "./enigmaSheet";
import { HARASS_H, HARASS_PAL, HARASS_PIX, HARASS_W } from "./harassSheet";
import { ICON_H, ICON_PAL, ICON_PIX, ICON_W } from "./iconSheet";
import { JOURNALIST_H, JOURNALIST_PAL, JOURNALIST_PIX, JOURNALIST_W } from "./journalistSheet";
import { KAREN_H, KAREN_PAL, KAREN_PIX, KAREN_W } from "./karenSheet";
import { ODRAMMA_H, ODRAMMA_PAL, ODRAMMA_PIX, ODRAMMA_W } from "./odrammaSheet";
import { SANDBAGS_H, SANDBAGS_PAL, SANDBAGS_PIX, SANDBAGS_W } from "./sandbagsSheet";
import { TURKEY_H, TURKEY_PAL, TURKEY_PIX, TURKEY_W } from "./turkeySheet";
import { VAKXIE_H, VAKXIE_PAL, VAKXIE_PIX, VAKXIE_W } from "./vakxieSheet";
import { VEGAN_H, VEGAN_PAL, VEGAN_PIX, VEGAN_W } from "./veganSheet";
import { BRANDER_H, BRANDER_PAL, BRANDER_PIX, BRANDER_W } from "./branderSheet";
import { BUSHED_H, BUSHED_PAL, BUSHED_PIX, BUSHED_W } from "./bushedSheet";
import { ELON_H, ELON_PAL, ELON_PIX, ELON_W } from "./elonSheet";
import { GRUMP_H, GRUMP_PAL, GRUMP_PIX, GRUMP_W } from "./grumpSheet";
import { HOOLI_H, HOOLI_PAL, HOOLI_PIX, HOOLI_W } from "./hooliSheet";
import { HOCKING_H, HOCKING_PAL, HOCKING_PIX, HOCKING_W } from "./hockingSheet";
import { LEGEND_H, LEGEND_PAL, LEGEND_PIX, LEGEND_W } from "./legendSheet";
import { QUIRK_H, QUIRK_PAL, QUIRK_PIX, QUIRK_W } from "./quirkSheet";
import { RICKY_H, RICKY_PAL, RICKY_PIX, RICKY_W } from "./rickySheet";
import { ROGEN_H, ROGEN_PAL, ROGEN_PIX, ROGEN_W } from "./rogenSheet";
import { type SheetDef } from "./sheetPaint";
import { TOMMY_H, TOMMY_PAL, TOMMY_PIX, TOMMY_W } from "./tommySheet";
import { VESTYT_H, VESTYT_PAL, VESTYT_PIX, VESTYT_W } from "./vestytSheet";

export const SHEET_HEROES: Record<string, SheetDef> = {
  "maga-grumptor": {
    id: "maga-grumptor",
    w: GRUMP_W,
    h: GRUMP_H,
    pal: GRUMP_PAL,
    pix: GRUMP_PIX,
    split: 86,
    gait: "step",
    skin: "#fc9751",
    blink: [
      { x: 36, y: 28, w: 7, h: 2 },
      { x: 50, y: 28, w: 7, h: 2 },
    ],
    flash: { x: 78, y: 32 },
  },
  "maga-hooli": {
    id: "maga-hooli",
    w: HOOLI_W,
    h: HOOLI_H,
    pal: HOOLI_PAL,
    pix: HOOLI_PIX,
    split: 90,
    gait: "step",
    skin: "#f8a664",
    blink: [
      { x: 37, y: 46, w: 5, h: 2 },
      { x: 44, y: 46, w: 4, h: 2 },
    ],
    flash: { x: 90, y: 66 },
    gap: 33,
  },
  "maga-ricky": {
    id: "maga-ricky",
    w: RICKY_W,
    h: RICKY_H,
    pal: RICKY_PAL,
    pix: RICKY_PIX,
    split: 72,
    gait: "roll",
    skin: "#fdc19e",
    blink: [
      { x: 46, y: 16, w: 5, h: 2 },
      { x: 54, y: 16, w: 6, h: 2 },
    ],
    flash: { x: 52, y: 50 },
    wheels: [
      { x: 32, y: 108 },
      { x: 60, y: 116 },
    ],
  },
  "wild-legend": {
    id: "wild-legend",
    w: LEGEND_W,
    h: LEGEND_H,
    pal: LEGEND_PAL,
    pix: LEGEND_PIX,
    split: 78,
    gait: "roll",
    skin: "#e8b896",
    blink: [
      { x: 38, y: 20, w: 6, h: 2 },
      { x: 50, y: 20, w: 6, h: 2 },
    ],
    flash: { x: 70, y: 48 },
  },
  "maga-rogentor": {
    id: "maga-rogentor",
    w: ROGEN_W,
    h: ROGEN_H,
    pal: ROGEN_PAL,
    pix: ROGEN_PIX,
    split: 84,
    gait: "step",
    skin: "#e8b896",
    blink: [
      { x: 40, y: 18, w: 5, h: 2 },
      { x: 50, y: 18, w: 5, h: 2 },
    ],
    flash: { x: 72, y: 30 },
    gap: 37,
  },
  "lw-hocking": {
    id: "lw-hocking",
    w: HOCKING_W,
    h: HOCKING_H,
    pal: HOCKING_PAL,
    pix: HOCKING_PIX,
    split: 72,
    gait: "roll",
    skin: "#e1b89d",
    blink: [
      { x: 40, y: 16, w: 5, h: 2 },
      { x: 48, y: 16, w: 5, h: 2 },
    ],
    flash: { x: 78, y: 38 },
  },
  "maga-quirk": {
    id: "maga-quirk",
    w: QUIRK_W,
    h: QUIRK_H,
    pal: QUIRK_PAL,
    pix: QUIRK_PIX,
    split: 83,
    gait: "step",
    skin: "#f1a066",
    blink: [
      { x: 42, y: 20, w: 4, h: 2 },
      { x: 49, y: 20, w: 4, h: 2 },
    ],
    flash: { x: 82, y: 28 },
    gap: 44,
  },
  "maga-tommy": {
    id: "maga-tommy",
    w: TOMMY_W,
    h: TOMMY_H,
    pal: TOMMY_PAL,
    pix: TOMMY_PIX,
    split: 82,
    gait: "step",
    skin: "#fcaf75",
    blink: [
      { x: 42, y: 20, w: 4, h: 2 },
      { x: 50, y: 20, w: 4, h: 2 },
    ],
    flash: { x: 82, y: 24 },
    gap: 42,
  },
  "maga-elonmolk": {
    id: "maga-elonmolk",
    w: ELON_W,
    h: ELON_H,
    pal: ELON_PAL,
    pix: ELON_PIX,
    split: 83,
    gait: "step",
    skin: "#fbb27a",
    blink: [
      { x: 38, y: 16, w: 4, h: 2 },
      { x: 45, y: 16, w: 4, h: 2 },
    ],
    flash: { x: 82, y: 22 },
    gap: 40,
  },
  "maga-boris": {
    id: "maga-boris",
    w: BORIS_W,
    h: BORIS_H,
    pal: BORIS_PAL,
    pix: BORIS_PIX,
    split: 84,
    gait: "step",
    skin: "#eaac6e",
    blink: [
      { x: 36, y: 16, w: 4, h: 2 },
      { x: 44, y: 16, w: 4, h: 2 },
    ],
    flash: { x: 82, y: 24 },
    gap: 41,
  },
  "maga-brander": {
    id: "maga-brander",
    w: BRANDER_W,
    h: BRANDER_H,
    pal: BRANDER_PAL,
    pix: BRANDER_PIX,
    split: 82,
    gait: "step",
    skin: "#fda063",
    blink: [
      { x: 36, y: 19, w: 4, h: 2 },
      { x: 43, y: 19, w: 4, h: 2 },
    ],
    flash: { x: 82, y: 22 },
    gap: 41,
  },
  "maga-vestyt": {
    id: "maga-vestyt",
    w: VESTYT_W,
    h: VESTYT_H,
    pal: VESTYT_PAL,
    pix: VESTYT_PIX,
    split: 83,
    gait: "step",
    skin: "#b78e6a",
    blink: [
      { x: 34, y: 16, w: 4, h: 2 },
      { x: 41, y: 16, w: 4, h: 2 },
    ],
    flash: { x: 82, y: 18 },
    gap: 42,
  },
  "maga-bushed": {
    id: "maga-bushed",
    w: BUSHED_W,
    h: BUSHED_H,
    pal: BUSHED_PAL,
    pix: BUSHED_PIX,
    split: 80,
    gait: "step",
    skin: "#d78f6d",
    blink: [
      { x: 34, y: 16, w: 4, h: 2 },
      { x: 42, y: 16, w: 4, h: 2 },
    ],
    flash: { x: 82, y: 20 },
    gap: 42,
  },
  "lw-sandbags": {
    id: "lw-sandbags",
    w: SANDBAGS_W,
    h: SANDBAGS_H,
    pal: SANDBAGS_PAL,
    pix: SANDBAGS_PIX,
    split: 85,
    gait: "step",
    skin: "#d3734e",
    blink: [
      { x: 34, y: 32, w: 5, h: 2 },
      { x: 44, y: 32, w: 5, h: 2 },
    ],
    flash: { x: 86, y: 35 },
    gap: 41,
  },
  "lw-bitenten": {
    id: "lw-bitenten",
    w: BITEN_W,
    h: BITEN_H,
    pal: BITEN_PAL,
    pix: BITEN_PIX,
    split: 87,
    gait: "step",
    skin: "#df9d7f",
    blink: [
      { x: 32, y: 38, w: 5, h: 2 },
      { x: 42, y: 38, w: 5, h: 2 },
    ],
    flash: { x: 78, y: 41 },
    gap: 37,
  },
  "lw-odramma": {
    id: "lw-odramma",
    w: ODRAMMA_W,
    h: ODRAMMA_H,
    pal: ODRAMMA_PAL,
    pix: ODRAMMA_PIX,
    split: 86,
    gait: "step",
    skin: "#ad6c4d",
    blink: [
      { x: 30, y: 38, w: 5, h: 2 },
      { x: 40, y: 38, w: 5, h: 2 },
    ],
    flash: { x: 76, y: 40 },
    gap: 37,
  },
  "lw-harass": {
    id: "lw-harass",
    w: HARASS_W,
    h: HARASS_H,
    pal: HARASS_PAL,
    pix: HARASS_PIX,
    split: 83,
    gait: "step",
    skin: "#db8756",
    blink: [
      { x: 36, y: 30, w: 5, h: 2 },
      { x: 46, y: 30, w: 5, h: 2 },
    ],
    flash: { x: 86, y: 33 },
    gap: 41,
  },
  "lw-youngturkey": {
    id: "lw-youngturkey",
    w: TURKEY_W,
    h: TURKEY_H,
    pal: TURKEY_PAL,
    pix: TURKEY_PIX,
    split: 74,
    gait: "unit",
    skin: "#de9971",
    blink: [
      { x: 68, y: 28, w: 5, h: 2 },
      { x: 78, y: 28, w: 5, h: 2 },
    ],
    flash: { x: 112, y: 58 },
    gap: 69,
  },
  "lw-vakxie": {
    id: "lw-vakxie",
    w: VAKXIE_W,
    h: VAKXIE_H,
    pal: VAKXIE_PAL,
    pix: VAKXIE_PIX,
    split: 87,
    gait: "step",
    skin: "#c78666",
    blink: [
      { x: 32, y: 36, w: 5, h: 2 },
      { x: 42, y: 36, w: 5, h: 2 },
    ],
    flash: { x: 76, y: 40 },
    gap: 38,
  },
  "lw-climate": {
    id: "lw-climate",
    w: CLIMATE_W,
    h: CLIMATE_H,
    pal: CLIMATE_PAL,
    pix: CLIMATE_PIX,
    split: 88,
    gait: "step",
    skin: "#d19845",
    blink: [
      { x: 28, y: 42, w: 5, h: 2 },
      { x: 38, y: 42, w: 5, h: 2 },
    ],
    flash: { x: 76, y: 44 },
    gap: 38,
  },
  "lw-journalist": {
    id: "lw-journalist",
    w: JOURNALIST_W,
    h: JOURNALIST_H,
    pal: JOURNALIST_PAL,
    pix: JOURNALIST_PIX,
    split: 84,
    gait: "step",
    skin: "#f5a369",
    blink: [
      { x: 32, y: 42, w: 5, h: 2 },
      { x: 42, y: 42, w: 5, h: 2 },
    ],
    flash: { x: 76, y: 40 },
    gap: 40,
  },
  "wild-icon": {
    id: "wild-icon",
    w: ICON_W,
    h: ICON_H,
    pal: ICON_PAL,
    pix: ICON_PIX,
    split: 91,
    gait: "step",
    skin: "#c28553",
    blink: [
      { x: 28, y: 40, w: 5, h: 2 },
      { x: 38, y: 40, w: 5, h: 2 },
    ],
    flash: { x: 72, y: 52 },
    gap: 45,
  },
  "wild-enigma": {
    id: "wild-enigma",
    w: ENIGMA_W,
    h: ENIGMA_H,
    pal: ENIGMA_PAL,
    pix: ENIGMA_PIX,
    split: 77,
    gait: "step",
    skin: "#b99f81",
    blink: [
      { x: 22, y: 16, w: 4, h: 2 },
      { x: 30, y: 16, w: 4, h: 2 },
    ],
    flash: { x: 56, y: 48 },
    gap: 34,
  },
  "wild-cartoons": {
    id: "wild-cartoons",
    w: CARTOONS_W,
    h: CARTOONS_H,
    pal: CARTOONS_PAL,
    pix: CARTOONS_PIX,
    split: 105,
    gait: "step",
    skin: "#feca93",
    blink: [
      { x: 48, y: 52, w: 8, h: 3 },
      { x: 66, y: 52, w: 8, h: 3 },
    ],
    flash: { x: 96, y: 58 },
    gap: 53,
  },
  "wild-dynasty": {
    id: "wild-dynasty",
    w: DYNASTY_W,
    h: DYNASTY_H,
    pal: DYNASTY_PAL,
    pix: DYNASTY_PIX,
    split: 90,
    gait: "unit",
    skin: "#e0ab83",
    blink: [
      { x: 18, y: 58, w: 4, h: 2 },
      { x: 26, y: 58, w: 4, h: 2 },
    ],
    flash: { x: 78, y: 62 },
  },
  "wild-karen": {
    id: "wild-karen",
    w: KAREN_W,
    h: KAREN_H,
    pal: KAREN_PAL,
    pix: KAREN_PIX,
    split: 81,
    gait: "step",
    skin: "#cd6d59",
    blink: [
      { x: 32, y: 36, w: 5, h: 2 },
      { x: 42, y: 36, w: 5, h: 2 },
    ],
    flash: { x: 78, y: 39 },
    gap: 38,
  },
  "wild-vegan": {
    id: "wild-vegan",
    w: VEGAN_W,
    h: VEGAN_H,
    pal: VEGAN_PAL,
    pix: VEGAN_PIX,
    split: 74,
    gait: "step",
    skin: "#da7641",
    blink: [
      { x: 40, y: 18, w: 4, h: 2 },
      { x: 50, y: 18, w: 4, h: 2 },
    ],
    flash: { x: 78, y: 22 },
    gap: 43,
  },
  "wild-butter": {
    id: "wild-butter",
    w: BUTTER_W,
    h: BUTTER_H,
    pal: BUTTER_PAL,
    pix: BUTTER_PIX,
    split: 96,
    gait: "step",
    skin: "#f0935f",
    blink: [
      { x: 40, y: 22, w: 4, h: 2 },
      { x: 50, y: 22, w: 4, h: 2 },
    ],
    flash: { x: 78, y: 48 },
    gap: 44,
  },
};

export function sheetDef(id: string): SheetDef | undefined {
  return SHEET_HEROES[id];
}
